# Generated by Django 3.2.12 on 2022-07-01 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_unknown_user',
            field=models.BooleanField(default=False),
        ),
    ]
