# Generated by Django 3.2.11 on 2022-07-04 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_auth', '0005_auto_20220704_1306'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expert',
            options={'verbose_name': 'Expert'},
        ),
    ]
