# Generated by Django 3.2.11 on 2022-07-04 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0011_alter_assessment_expert'),
        ('my_auth', '0006_alter_expert_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Expert',
        ),
    ]
