# Generated by Django 3.2.11 on 2022-02-11 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='criteria',
            options={'ordering': ['code'], 'verbose_name': 'Critère', 'verbose_name_plural': '3. Critères'},
        ),
        migrations.AlterModelOptions(
            name='marker',
            options={'ordering': ['code'], 'verbose_name': 'Marqueur', 'verbose_name_plural': '2. Marqueurs'},
        ),
        migrations.AlterModelOptions(
            name='pillar',
            options={'ordering': ['code'], 'verbose_name': 'Pilier', 'verbose_name_plural': '1. Piliers'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['code'], 'verbose_name': 'Question', 'verbose_name_plural': '4. Questions'},
        ),
        migrations.RenameField(
            model_name='question',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='criteria',
            name='order',
        ),
    ]
