# Generated by Django 3.2.11 on 2022-01-26 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='tagline',
            field=models.CharField(default='', max_length=127),
        ),
    ]
