# Generated by Django 3.2.12 on 2022-03-03 15:04

from django.db import migrations


def create_pillars(apps, _):
    Pillar = apps.get_model("open_democracy_back", "Pillar")
    for name in [
        "représentation",
        "transparence",
        "participation",
        "coopération",
    ]:
        code = name[0].upper()
        Pillar.objects.create(code=code, name=name)


def remove_pillars(apps, _):
    Pillar = apps.get_model("open_democracy_back", "Pillar")
    Pillar.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("open_democracy_back", "0001_initial"),
    ]

    operations = [migrations.RunPython(create_pillars, remove_pillars)]
