# Generated by Django 3.2.11 on 2022-03-04 08:24

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0002_auto_20220303_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='criteria',
            name='description',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Description pour le référentiel', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='criteria',
            name='score_1',
            field=models.TextField(blank=True, default='', help_text='Description pour le référentiel', verbose_name='Score = 1'),
        ),
        migrations.AddField(
            model_name='criteria',
            name='score_2',
            field=models.TextField(blank=True, default='', help_text='Description pour le référentiel', verbose_name='Score = 2'),
        ),
        migrations.AddField(
            model_name='criteria',
            name='score_3',
            field=models.TextField(blank=True, default='', help_text='Description pour le référentiel', verbose_name='Score = 3'),
        ),
        migrations.AddField(
            model_name='criteria',
            name='score_4',
            field=models.TextField(blank=True, default='', help_text='Description pour le référentiel', verbose_name='Score = 4'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='score_1',
            field=models.TextField(blank=True, default='', help_text='Description pour le référentiel', verbose_name='Score = 1'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='score_2',
            field=models.TextField(blank=True, default='', help_text='Description pour le référentiel', verbose_name='Score = 2'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='score_3',
            field=models.TextField(blank=True, default='', help_text='Description pour le référentiel', verbose_name='Score = 3'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='score_4',
            field=models.TextField(blank=True, default='', help_text='Description pour le référentiel', verbose_name='Score = 4'),
        ),
    ]
