# Generated by Django 3.2.12 on 2022-06-30 15:07

from django.db import migrations

def create_assessment_types(apps, _):
    AssessmentType = apps.get_model("open_democracy_back", "AssessmentType")
    for assessment_type, name in [
        ("quick", "Diagnostic rapide"),
        ("participative", "Evaluation participative"),
        ("with_expert", "Evaluation avec experts"),
    ]:
        AssessmentType.objects.create(assessment_type=assessment_type, name=name)


def remove_assessment_types(apps, _):
    AssessmentType = apps.get_model("open_democracy_back", "AssessmentType")
    AssessmentType.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0002_add_pillars'),
    ]

    operations = [
        migrations.RunPython(create_assessment_types, remove_assessment_types),
    ]
