# Generated by Django 3.2.11 on 2022-02-15 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0003_profiling_profilingresponsechoice'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='criteria',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='marker',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='pillar',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='profiling',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='profilingresponsechoice',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='responsechoice',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='criteria',
            name='locale',
        ),
        migrations.RemoveField(
            model_name='criteria',
            name='translation_key',
        ),
        migrations.RemoveField(
            model_name='marker',
            name='locale',
        ),
        migrations.RemoveField(
            model_name='marker',
            name='translation_key',
        ),
        migrations.RemoveField(
            model_name='pillar',
            name='locale',
        ),
        migrations.RemoveField(
            model_name='pillar',
            name='sort_order',
        ),
        migrations.RemoveField(
            model_name='pillar',
            name='translation_key',
        ),
        migrations.RemoveField(
            model_name='profiling',
            name='locale',
        ),
        migrations.RemoveField(
            model_name='profiling',
            name='translation_key',
        ),
        migrations.RemoveField(
            model_name='profilingresponsechoice',
            name='locale',
        ),
        migrations.RemoveField(
            model_name='profilingresponsechoice',
            name='translation_key',
        ),
        migrations.RemoveField(
            model_name='question',
            name='locale',
        ),
        migrations.RemoveField(
            model_name='question',
            name='translation_key',
        ),
        migrations.RemoveField(
            model_name='responsechoice',
            name='locale',
        ),
        migrations.RemoveField(
            model_name='responsechoice',
            name='translation_key',
        ),
    ]
