# Generated by Django 3.2.11 on 2022-02-15 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0004_auto_20220215_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionfilter',
            name='conditional_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions_that_depend_on_me', to='open_democracy_back.question', verbose_name='Filtre par question'),
        ),
    ]
