# Generated by Django 3.2.11 on 2022-03-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0004_assessment_assessmentzipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='name',
            field=models.CharField(default='', max_length=125),
        ),
    ]
