# Generated by Django 3.2.11 on 2022-03-10 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0005_assessment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='criteria',
            name='concatenated_code',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AddField(
            model_name='marker',
            name='concatenated_code',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AddField(
            model_name='question',
            name='concatenated_code',
            field=models.CharField(default='', max_length=8),
        ),
    ]
