# Generated by Django 3.2.12 on 2022-07-07 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0005_rgpdsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='is_current',
            field=models.BooleanField(default=True),
        ),
    ]
