# Generated by Django 3.2.11 on 2022-03-10 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0005_assessment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='criteria',
            name='concatenated_code',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AddField(
            model_name='marker',
            name='concatenated_code',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AddField(
            model_name='question',
            name='concatenated_code',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='marker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='criterias', to='open_democracy_back.marker'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='pillar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='markers', to='open_democracy_back.pillar'),
        ),
        migrations.AlterField(
            model_name='question',
            name='criteria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='open_democracy_back.criteria'),
        ),
    ]
