# Generated by Django 3.2.11 on 2022-01-28 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0005_auto_20220128_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='max',
            field=models.IntegerField(blank=True, null=True, verbose_name='Valeur maximale'),
        ),
        migrations.AddField(
            model_name='question',
            name='min',
            field=models.IntegerField(blank=True, null=True, verbose_name='Valeur minimale'),
        ),
    ]
