# Generated by Django 3.2.11 on 2022-07-07 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('open_democracy_back', '0005_rgpdsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True, verbose_name='email address')),
            ],
        ),
        migrations.AddField(
            model_name='assessment',
            name='expert',
            field=models.ForeignKey(blank=True, help_text="Pour ajouter un expert à la liste il faut créer / modifier l'utilisateur correspondant, aller dans l'onglet rôles et cocher la case Experts", limit_choices_to={'groups__name': 'Experts'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to=settings.AUTH_USER_MODEL, verbose_name='Expert'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='royalty_payed',
            field=models.BooleanField(default=False, verbose_name='Redevance payée'),
        ),
        migrations.AlterField(
            model_name='closedwithscalecategoryresponse',
            name='response_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='open_democracy_back.responsechoice'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('name', models.CharField(default='', max_length=128, verbose_name='Nom')),
                ('closed', models.BooleanField(default=False)),
                ('animator', models.ForeignKey(limit_choices_to={'groups__name': 'Experts'}, on_delete=django.db.models.deletion.CASCADE, related_name='workshops', to=settings.AUTH_USER_MODEL)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshops', to='open_democracy_back.assessment')),
            ],
            options={
                'verbose_name': 'Atelier',
            },
        ),
        migrations.AddField(
            model_name='participation',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='open_democracy_back.participant'),
        ),
        migrations.AddField(
            model_name='participation',
            name='workshop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='open_democracy_back.workshop'),
        ),
        migrations.AlterUniqueTogether(
            name='participation',
            unique_together={('user', 'participant', 'assessment')},
        ),
    ]
