# Generated by Django 3.2.11 on 2022-07-04 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0006_auto_20220701_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closedwithscalecategoryresponse',
            name='response_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='open_democracy_back.responsechoice'),
        ),
    ]
