# Generated by Django 3.2.11 on 2022-03-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0006_auto_20220310_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='false_associated_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='Score associé à une réponse négative'),
        ),
        migrations.AddField(
            model_name='question',
            name='max_associated_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='Score associé à la valeur maximale'),
        ),
        migrations.AddField(
            model_name='question',
            name='max_label',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Label de la valeur maximale'),
        ),
        migrations.AddField(
            model_name='question',
            name='min_associated_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='Score associé à la valeur minimale'),
        ),
        migrations.AddField(
            model_name='question',
            name='min_label',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Label de la valeur minimale'),
        ),
        migrations.AddField(
            model_name='question',
            name='true_associated_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='Score associé à une réponse positive'),
        ),
        migrations.AddField(
            model_name='responsechoice',
            name='associated_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='Score associé'),
        ),
        migrations.AlterField(
            model_name='question',
            name='name',
            field=models.CharField(default='', max_length=125, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_statement',
            field=models.TextField(default='', verbose_name='Enoncé de la question'),
        ),
    ]
