# Generated by Django 3.2.11 on 2022-07-11 09:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('open_democracy_back', '0006_auto_20220707_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='expert',
        ),
        migrations.AddField(
            model_name='assessment',
            name='experts',
            field=models.ManyToManyField(help_text="Pour ajouter un expert à la liste il faut créer / modifier l'utilisateur correspondant, aller dans l'onglet rôles et cocher la case Experts", limit_choices_to={'groups__name': 'Experts'}, related_name='assessments', to=settings.AUTH_USER_MODEL, verbose_name='Experts'),
        ),
    ]
