# Generated by Django 3.2.11 on 2022-01-31 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0006_auto_20220128_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='objective',
        ),
        migrations.AddField(
            model_name='question',
            name='method',
            field=models.CharField(blank=True, choices=[('quantitative', 'quantitative'), ('qualitative', 'qualitative')], max_length=32),
        ),
        migrations.AddField(
            model_name='question',
            name='objectivity',
            field=models.CharField(choices=[('objective', 'objective'), ('subjective', 'subjective')], default='subjective', max_length=32),
        ),
        migrations.AddField(
            model_name='question',
            name='title',
            field=models.CharField(default='', max_length=125),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(default=''),
        ),
    ]
