# Generated by Django 3.2.11 on 2022-07-07 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('wagtailcore', '0066_collection_management_permissions'),
        ('open_democracy_back', '0006_auto_20220707_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluationquestionnairepage',
            name='role_question_description',
        ),
        migrations.RemoveField(
            model_name='evaluationquestionnairepage',
            name='role_question_title',
        ),
        migrations.CreateModel(
            name='ResultsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('tag_line', models.CharField(default='', max_length=510, verbose_name="Phrase d'accroche")),
                ('intro_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Page de résultats',
            },
            bases=('wagtailcore.page',),
        ),
    ]
