# Generated by Django 3.2.11 on 2022-03-10 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0007_auto_20220310_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='conditional_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules_that_depend_on_me', to='open_democracy_back.role', verbose_name='Filtre par rôle'),
        ),
    ]
