# Generated by Django 3.2.11 on 2022-01-31 19:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import modelcluster.fields
import open_democracy_back.models


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0007_auto_20220131_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('conditional_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='open_democracy_back.question', verbose_name='Filtre par question')),
                ('question', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_filters', to='open_democracy_back.question')),
                ('response', models.ForeignKey(limit_choices_to=open_democracy_back.models.QuestionFilter.get_possible_response, on_delete=django.db.models.deletion.CASCADE, to='open_democracy_back.responsechoice')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
