# Generated by Django 3.2.11 on 2022-07-07 16:07

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0007_auto_20220707_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultspage',
            name='introduction',
            field=wagtail.core.fields.RichTextField(default='', verbose_name='Introduction'),
        ),
    ]
