# Generated by Django 3.2.11 on 2022-02-16 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0007_auto_20220216_1114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionfilter',
            old_name='numerical_first_operator',
            new_name='numerical_operator',
        ),
        migrations.RenameField(
            model_name='questionfilter',
            old_name='numerical_first_value',
            new_name='numerical_value',
        ),
        migrations.RemoveField(
            model_name='questionfilter',
            name='numerical_second_operator',
        ),
        migrations.RemoveField(
            model_name='questionfilter',
            name='numerical_second_value',
        ),
    ]
