# Generated by Django 3.2.11 on 2022-07-04 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0007_alter_closedwithscalecategoryresponse_response_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='royalty_payed',
            field=models.BooleanField(default=False, verbose_name='Redevance payée'),
        ),
    ]
