# Generated by Django 3.2.11 on 2022-02-17 10:07

import _operator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0008_auto_20220216_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionfilter',
            name='intersection_operator',
            field=models.CharField(blank=True, choices=[('and', 'et'), ('or', 'ou'), ('not', 'non')], max_length=8),
        ),
        migrations.AlterField(
            model_name='questionfilter',
            name='numerical_operator',
            field=models.CharField(blank=True, choices=[(_operator.lt, '<'), (_operator.gt, '>'), (_operator.le, '<='), (_operator.ge, '>='), (_operator.ne, '!='), (_operator.eq, '=')], max_length=8),
        ),
    ]
