# Generated by Django 3.2.11 on 2022-07-10 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0006_auto_20220707_1323'),
        ('open_democracy_back', '0008_resultspage_introduction'),
    ]

    operations = [
    ]
