# Generated by Django 3.2.11 on 2022-07-11 13:37

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('wagtailimages', '0023_add_choose_permissions'),
        ('open_democracy_back', '0008_auto_20220711_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criteria',
            name='score_1',
        ),
        migrations.RemoveField(
            model_name='criteria',
            name='score_2',
        ),
        migrations.RemoveField(
            model_name='criteria',
            name='score_3',
        ),
        migrations.RemoveField(
            model_name='criteria',
            name='score_4',
        ),
        migrations.AddField(
            model_name='criteria',
            name='improvement_1',
            field=models.TextField(blank=True, default='', help_text="Point d'amélioration relevé pour une évaluation si le calcul de son score est de 1", verbose_name="Point d'amélioration 1"),
        ),
        migrations.AddField(
            model_name='criteria',
            name='improvement_2',
            field=models.TextField(blank=True, default='', help_text="Point d'amélioration relevé pour une évaluation si le calcul de son score est de 2", verbose_name="Point d'amélioration 2"),
        ),
        migrations.AddField(
            model_name='criteria',
            name='strength_3',
            field=models.TextField(blank=True, default='', help_text='Point fort relevé pour une évaluation si le calcul de son score est de 3', verbose_name='Point fort 3'),
        ),
        migrations.AddField(
            model_name='criteria',
            name='strength_4',
            field=models.TextField(blank=True, default='', help_text='Point fort relevé pour une évaluation si le calcul de son score est de 4', verbose_name='Point fort 4'),
        ),
        migrations.AddField(
            model_name='marker',
            name='improvement_1',
            field=models.TextField(blank=True, default='', help_text="Point d'amélioration relevé pour une évaluation si le calcul de son score est de 1", verbose_name="Point d'amélioration 1"),
        ),
        migrations.AddField(
            model_name='marker',
            name='improvement_2',
            field=models.TextField(blank=True, default='', help_text="Point d'amélioration relevé pour une évaluation si le calcul de son score est de 2", verbose_name="Point d'amélioration 2"),
        ),
        migrations.AddField(
            model_name='marker',
            name='strength_3',
            field=models.TextField(blank=True, default='', help_text='Point fort relevé pour une évaluation si le calcul de son score est de 3', verbose_name='Point fort 3'),
        ),
        migrations.AddField(
            model_name='marker',
            name='strength_4',
            field=models.TextField(blank=True, default='', help_text='Point fort relevé pour une évaluation si le calcul de son score est de 4', verbose_name='Point fort 4'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='explanatory',
            field=wagtail.core.fields.StreamField([('category', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(label='Titre')), ('description', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'ol', 'ul'], label='Description'))], label='Catégorie', label_format='Catégorie : {title}'))], blank=True, verbose_name='Explicatif du critère (sources, exemples, obligations légales ...)'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='score_1',
            field=models.TextField(blank=True, default='', help_text='Signification du résultat 1 dans le DémoMètre', verbose_name='Signification'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='score_2',
            field=models.TextField(blank=True, default='', help_text='Signification du résultat 2 dans le DémoMètre', verbose_name='Signification'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='score_3',
            field=models.TextField(blank=True, default='', help_text='Signification du résultat 3 dans le DémoMètre', verbose_name='Signification'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='score_4',
            field=models.TextField(blank=True, default='', help_text='Signification du résultat 4 dans le DémoMètre', verbose_name='Signification'),
        ),
        migrations.CreateModel(
            name='ResultsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('tag_line', models.CharField(default='', max_length=510, verbose_name="Phrase d'accroche")),
                ('introduction', wagtail.core.fields.RichTextField(default='', verbose_name='Introduction')),
                ('intro_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Page de résultats',
            },
            bases=('wagtailcore.page',),
        ),
    ]
