# Generated by Django 3.2.12 on 2022-07-11 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0008_auto_20220711_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='is_current',
            field=models.BooleanField(default=True),
        ),
    ]
