# Generated by Django 3.2.12 on 2022-03-11 16:11

from django.db import migrations
from open_democracy_back.data.regions import REGIONS
from open_democracy_back.data.departements import DEPARTEMENTS
from open_democracy_back.data.epci import EPCI as EPCIS
from open_democracy_back.data.communes import COMMUNES


def addMunicipalitiesAndEPCI(apps, _):
    Municipality = apps.get_model("open_democracy_back", "Municipality")
    Region = apps.get_model("open_democracy_back", "Region")
    Department = apps.get_model("open_democracy_back", "Department")
    EPCI = apps.get_model("open_democracy_back", "EPCI")
    ZipCode = apps.get_model("open_democracy_back", "ZipCode")

    bulk_region = []
    for region in REGIONS:
        bulk_region.append(Region(name=region["nom"], code=region["code"]))
    bulk_region.append(Region(name="Région d'outre-mer", code="97"))
    Region.objects.bulk_create(bulk_region)
    regions = { region.code: region for region in Region.objects.all() }

    bulk_department = []
    for department in DEPARTEMENTS:
        bulk_department.append(Department(name=department["nom"], code=department["code"], region=regions[department["region"]]))
    bulk_department.append(Department(name="Département d'outre-mer", code="97", region=regions["97"]))

    Department.objects.bulk_create(bulk_department)
    departments = { department.code: department for department in Department.objects.all() }

    for commune_dict in COMMUNES:
        department_code = commune_dict.get("departement", "97")
        commune = Municipality(code=commune_dict["code"], name=commune_dict["nom"], department=departments[department_code], population=commune_dict.get("population", 0))
        commune.save()
        for zip_code_value in commune_dict.get("codesPostaux", []):
            ZipCode(code=zip_code_value, municipality=commune).save()

    for epci_dict in EPCIS:
        member_codes = [member["code"] for member in epci_dict["membres"]]
        municipalities = Municipality.objects.filter(code__in=member_codes)
        epci = EPCI(name=epci_dict["nom"], population=epci_dict.get("populationTotale") or epci_dict.get("populationMunicipale", 0))
        epci.save()
        epci.municipalities.add(*municipalities)


def removeMunicipalitiesAndEPCI(apps, _):
    apps.get_model("open_democracy_back", "Municipality").objects.all().delete()
    apps.get_model("open_democracy_back", "Region").objects.all().delete()
    apps.get_model("open_democracy_back", "Department").objects.all().delete()
    apps.get_model("open_democracy_back", "EPCI").objects.all().delete()
    apps.get_model("open_democracy_back", "ZipCode").objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0009_auto_20220311_1611'),
    ]

    operations = [
        migrations.RunPython(addMunicipalitiesAndEPCI, removeMunicipalitiesAndEPCI),
    ]
