# Generated by Django 3.2.11 on 2022-07-10 19:11

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0009_merge_20220710_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criteria',
            name='score_1',
        ),
        migrations.RemoveField(
            model_name='criteria',
            name='score_2',
        ),
        migrations.RemoveField(
            model_name='criteria',
            name='score_3',
        ),
        migrations.RemoveField(
            model_name='criteria',
            name='score_4',
        ),
        migrations.AddField(
            model_name='marker',
            name='strength_3',
            field=models.TextField(blank=True, default='', help_text='Point fort relevé pour une évaluation suite au calcul de son score', verbose_name='Point fort pour score = 3'),
        ),
        migrations.AddField(
            model_name='marker',
            name='strength_4',
            field=models.TextField(blank=True, default='', help_text='Point fort relevé pour une évaluation suite au calcul de son score', verbose_name='Point fort pour score = 4'),
        ),
        migrations.AddField(
            model_name='marker',
            name='weakness_1',
            field=models.TextField(blank=True, default='', help_text='Point faible relevé pour une évaluation suite au calcul de son score', verbose_name='Point faible pour score = 1'),
        ),
        migrations.AddField(
            model_name='marker',
            name='weakness_2',
            field=models.TextField(blank=True, default='', help_text='Point faible relevé pour une évaluation suite au calcul de son score', verbose_name='Point faible pour score = 2'),
        ),
        migrations.AddField(
            model_name='pillar',
            name='score_1',
            field=models.TextField(blank=True, default='', help_text='Description de la signification du résultat 1 du DémoMètre', verbose_name='Signification du score = 1'),
        ),
        migrations.AddField(
            model_name='pillar',
            name='score_2',
            field=models.TextField(blank=True, default='', help_text='Description de la signification du résultat 2 du DémoMètre', verbose_name='Signification du score = 2'),
        ),
        migrations.AddField(
            model_name='pillar',
            name='score_3',
            field=models.TextField(blank=True, default='', help_text='Description de la signification du résultat 3 du DémoMètre', verbose_name='Signification du score = 3'),
        ),
        migrations.AddField(
            model_name='pillar',
            name='score_4',
            field=models.TextField(blank=True, default='', help_text='Description de la signification du résultat 4 du DémoMètre', verbose_name='Signification du score = 4'),
        ),
        migrations.AddField(
            model_name='pillar',
            name='strength_3',
            field=models.TextField(blank=True, default='', help_text='Point fort relevé pour une évaluation suite au calcul de son score', verbose_name='Point fort pour score = 3'),
        ),
        migrations.AddField(
            model_name='pillar',
            name='strength_4',
            field=models.TextField(blank=True, default='', help_text='Point fort relevé pour une évaluation suite au calcul de son score', verbose_name='Point fort pour score = 4'),
        ),
        migrations.AddField(
            model_name='pillar',
            name='weakness_1',
            field=models.TextField(blank=True, default='', help_text='Point faible relevé pour une évaluation suite au calcul de son score', verbose_name='Point faible pour score = 1'),
        ),
        migrations.AddField(
            model_name='pillar',
            name='weakness_2',
            field=models.TextField(blank=True, default='', help_text='Point faible relevé pour une évaluation suite au calcul de son score', verbose_name='Point faible pour score = 2'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='explanatory',
            field=wagtail.core.fields.StreamField([('category', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(label='Titre')), ('description', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'ol', 'ul'], label='Description'))], label='Catégorie', label_format='Catégorie : {title}'))], blank=True, verbose_name='Explicatif du critère (sources, exemples, obligations légales ...)'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='score_1',
            field=models.TextField(blank=True, default='', help_text='Description de la signification du résultat 1 du DémoMètre', verbose_name='Signification du score = 1'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='score_2',
            field=models.TextField(blank=True, default='', help_text='Description de la signification du résultat 2 du DémoMètre', verbose_name='Signification du score = 2'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='score_3',
            field=models.TextField(blank=True, default='', help_text='Description de la signification du résultat 3 du DémoMètre', verbose_name='Signification du score = 3'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='score_4',
            field=models.TextField(blank=True, default='', help_text='Description de la signification du résultat 4 du DémoMètre', verbose_name='Signification du score = 4'),
        ),
    ]
