# Generated by Django 3.2.11 on 2022-07-04 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_auth', '0006_alter_expert_options'),
        ('open_democracy_back', '0009_alter_assessment_expert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='expert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='my_auth.expert', verbose_name='Expert'),
        ),
    ]
