# Generated by Django 3.2.11 on 2022-02-17 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0009_auto_20220217_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionfilter',
            name='intersection_operator',
            field=models.CharField(blank=True, choices=[('and', 'et'), ('or', 'ou')], max_length=8),
        ),
        migrations.AlterField(
            model_name='questionfilter',
            name='numerical_operator',
            field=models.CharField(blank=True, choices=[('<', '<'), ('>', '>'), ('<=', '<='), ('>=', '>='), ('!=', '!='), ('=', '=')], max_length=8),
        ),
    ]
