# Generated by Django 3.2.11 on 2022-07-11 21:20

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('wagtailimages', '0023_add_choose_permissions'),
        ('open_democracy_back', '0009_participation_is_current'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criteria',
            name='score_1',
        ),
        migrations.RemoveField(
            model_name='criteria',
            name='score_2',
        ),
        migrations.RemoveField(
            model_name='criteria',
            name='score_3',
        ),
        migrations.RemoveField(
            model_name='criteria',
            name='score_4',
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(default='', help_text='Permet de répondre à la même question pour différentes catégories', max_length=128, verbose_name='Categorie'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='explanatory',
            field=wagtail.core.fields.StreamField([('category', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(label='Titre')), ('description', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'ol', 'ul'], label='Description'))], label='Catégorie', label_format='Catégorie : {title}'))], blank=True, verbose_name='Explicatif du critère (sources, exemples, obligations légales ...)'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='score_1',
            field=models.TextField(blank=True, default='', help_text='Signification du résultat 1, affiché dans le DémoMètre', verbose_name='Score = 1 (Signification)'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='score_2',
            field=models.TextField(blank=True, default='', help_text='Signification du résultat 2, affiché dans le DémoMètre', verbose_name='Score = 2 (Signification)'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='score_3',
            field=models.TextField(blank=True, default='', help_text='Signification du résultat 3, affiché dans le DémoMètre', verbose_name='Score = 3 (Signification)'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='score_4',
            field=models.TextField(blank=True, default='', help_text='Signification du résultat 4, affiché dans le DémoMètre', verbose_name='Score = 4 (Signification)'),
        ),
        migrations.CreateModel(
            name='ResultsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('tag_line', models.CharField(default='', max_length=510, verbose_name="Phrase d'accroche")),
                ('introduction', wagtail.core.fields.RichTextField(default='', verbose_name='Introduction')),
                ('intro_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Page de résultats',
            },
            bases=('wagtailcore.page',),
        ),
    ]
