# Generated by Django 3.2.11 on 2022-07-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '00010_auto_20220711_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criteria',
            name='improvement_1',
        ),
        migrations.RemoveField(
            model_name='criteria',
            name='improvement_2',
        ),
        migrations.RemoveField(
            model_name='criteria',
            name='strength_3',
        ),
        migrations.RemoveField(
            model_name='criteria',
            name='strength_4',
        ),
        migrations.RemoveField(
            model_name='marker',
            name='improvement_1',
        ),
        migrations.RemoveField(
            model_name='marker',
            name='improvement_2',
        ),
        migrations.RemoveField(
            model_name='marker',
            name='strength_3',
        ),
        migrations.RemoveField(
            model_name='marker',
            name='strength_4',
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(default='', help_text='Permet de répondre à la même question pour différentes catégories', max_length=128, verbose_name='Categorie'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='score_1',
            field=models.TextField(blank=True, default='', help_text='Signification du résultat 1, affiché dans le DémoMètre', verbose_name='Score = 1 (Signification)'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='score_2',
            field=models.TextField(blank=True, default='', help_text='Signification du résultat 2, affiché dans le DémoMètre', verbose_name='Score = 2 (Signification)'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='score_3',
            field=models.TextField(blank=True, default='', help_text='Signification du résultat 3, affiché dans le DémoMètre', verbose_name='Score = 3 (Signification)'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='score_4',
            field=models.TextField(blank=True, default='', help_text='Signification du résultat 4, affiché dans le DémoMètre', verbose_name='Score = 4 (Signification)'),
        ),
    ]
