# Generated by Django 3.2.11 on 2022-07-13 08:31

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0010_auto_20220711_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultspage',
            name='tag_line_no_results',
            field=models.CharField(default='', max_length=510, verbose_name='Consigne si aucun résultat publié'),
        ),
        migrations.AlterField(
            model_name='assessmentrepresentativity',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representativities', to='open_democracy_back.assessment'),
        ),
        migrations.AlterField(
            model_name='assessmentrepresentativity',
            name='representativity_criteria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representativities', to='open_democracy_back.representativitycriteria'),
        ),
        migrations.AlterField(
            model_name='resultspage',
            name='introduction',
            field=wagtail.core.fields.RichTextField(blank=True, default='', verbose_name='Introduction'),
        ),
        migrations.AlterField(
            model_name='resultspage',
            name='tag_line',
            field=models.CharField(default='', max_length=510, verbose_name='Consigne'),
        ),
        migrations.CreateModel(
            name='RepresentativityCriteriaRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ignore_for_acceptability_threshold', models.BooleanField(default=False, help_text='Ex: binaire pour la parité', verbose_name="Ne pas compter pour le seuil d'acceptabilité minimal")),
                ('totally_ignore', models.BooleanField(default=False, verbose_name='Ignorer totalement')),
                ('representativity_criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='open_democracy_back.representativitycriteria')),
                ('response_choice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='representativity_criteria_rule', to='open_democracy_back.responsechoice', verbose_name='Réponse')),
            ],
            options={
                'unique_together': {('representativity_criteria', 'response_choice')},
            },
        ),
    ]
