# Generated by Django 3.2.11 on 2022-03-15 08:28

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields

from open_democracy_back.models.assessment_models import Municipality


def addMunicipalityOrderByEPCI(apps, _):
    EPCI = apps.get_model("open_democracy_back", "EPCI")
    MunicipalityOrderByEPCI = apps.get_model(
        "open_democracy_back", "MunicipalityOrderByEPCI"
    )
    epcis = EPCI.objects.all()
    for epci in epcis:
        for municipality in epci.municipalities.all():
            MunicipalityOrderByEPCI(epci=epci, municipality=municipality).save()
        epci.municipalities.clear()


def removeMunicipalityOrderByEPCI(apps, _):
    MunicipalityOrderByEPCI = apps.get_model(
        "open_democracy_back", "MunicipalityOrderByEPCI"
    )
    municipalitiyOrderByEPCIs = MunicipalityOrderByEPCI.objects.all()
    for municipalitiyOrderByEPCI in municipalitiyOrderByEPCIs:
        municipalitiyOrderByEPCI.epci.municipalities.add(
            municipalitiyOrderByEPCI.municipality
        )
    municipalitiyOrderByEPCIs.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("open_democracy_back", "0010_auto_20220311_1611"),
    ]

    operations = [
        migrations.AlterField(
            model_name="zipcode",
            name="municipality",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="zip_codes",
                to="open_democracy_back.municipality",
                verbose_name="Municipalité",
            ),
        ),
        migrations.CreateModel(
            name="MunicipalityOrderByEPCI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "epci",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_municipalities_ordered",
                        to="open_democracy_back.epci",
                    ),
                ),
                (
                    "municipality",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="open_democracy_back.municipality",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.RunPython(addMunicipalityOrderByEPCI, removeMunicipalityOrderByEPCI),
    ]
