# Generated by Django 3.2.11 on 2022-07-10 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0010_auto_20220710_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='score_1',
            field=models.TextField(blank=True, default='', help_text='Signification du résultat 1 dans le DémoMètre', verbose_name='Signification'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='score_2',
            field=models.TextField(blank=True, default='', help_text='Signification du résultat 2 dans le DémoMètre', verbose_name='Signification'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='score_3',
            field=models.TextField(blank=True, default='', help_text='Signification du résultat 3 dans le DémoMètre', verbose_name='Signification'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='score_4',
            field=models.TextField(blank=True, default='', help_text='Signification du résultat 4 dans le DémoMètre', verbose_name='Signification'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='strength_3',
            field=models.TextField(blank=True, default='', help_text='Point fort relevé pour une évaluation si le calcul de son score est de 3', verbose_name='Point fort'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='strength_4',
            field=models.TextField(blank=True, default='', help_text='Point fort relevé pour une évaluation si le calcul de son score est de 4', verbose_name='Point fort'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='weakness_1',
            field=models.TextField(blank=True, default='', help_text='Point faible relevé pour une évaluation si le calcul de son score est de 1', verbose_name='Point faible'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='weakness_2',
            field=models.TextField(blank=True, default='', help_text='Point faible relevé pour une évaluation si le calcul de son score est de 2', verbose_name='Point faible'),
        ),
        migrations.AlterField(
            model_name='pillar',
            name='score_1',
            field=models.TextField(blank=True, default='', help_text='Signification du résultat 1 dans le DémoMètre', verbose_name='Signification'),
        ),
        migrations.AlterField(
            model_name='pillar',
            name='score_2',
            field=models.TextField(blank=True, default='', help_text='Signification du résultat 2 dans le DémoMètre', verbose_name='Signification'),
        ),
        migrations.AlterField(
            model_name='pillar',
            name='score_3',
            field=models.TextField(blank=True, default='', help_text='Signification du résultat 3 dans le DémoMètre', verbose_name='Signification'),
        ),
        migrations.AlterField(
            model_name='pillar',
            name='score_4',
            field=models.TextField(blank=True, default='', help_text='Signification du résultat 4 dans le DémoMètre', verbose_name='Signification'),
        ),
        migrations.AlterField(
            model_name='pillar',
            name='strength_3',
            field=models.TextField(blank=True, default='', help_text='Point fort relevé pour une évaluation si le calcul de son score est de 3', verbose_name='Point fort'),
        ),
        migrations.AlterField(
            model_name='pillar',
            name='strength_4',
            field=models.TextField(blank=True, default='', help_text='Point fort relevé pour une évaluation si le calcul de son score est de 4', verbose_name='Point fort'),
        ),
        migrations.AlterField(
            model_name='pillar',
            name='weakness_1',
            field=models.TextField(blank=True, default='', help_text='Point faible relevé pour une évaluation si le calcul de son score est de 1', verbose_name='Point faible'),
        ),
        migrations.AlterField(
            model_name='pillar',
            name='weakness_2',
            field=models.TextField(blank=True, default='', help_text='Point faible relevé pour une évaluation si le calcul de son score est de 2', verbose_name='Point faible'),
        ),
    ]
