# Generated by Django 3.2.11 on 2022-07-04 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('open_democracy_back', '0010_alter_assessment_expert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='expert',
            field=models.ForeignKey(blank=True, limit_choices_to={'group__name': 'Experts'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to=settings.AUTH_USER_MODEL, verbose_name='Expert'),
        ),
    ]
