# Generated by Django 3.2.13 on 2022-07-12 13:11

from django.db import migrations, models
import django.db.models.deletion
import open_democracy_back.models.contents_models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('open_democracy_back', '0011_auto_20220712_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectpage',
            name='who_committee_sub_block_introduction',
        ),
        migrations.AddField(
            model_name='projectpage',
            name='who_committee_sub_block_description',
            field=wagtail.core.fields.RichTextField(blank=True, default='', verbose_name='Comité d’orientation - description'),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='who_committee_sub_block_data',
            field=wagtail.core.fields.StreamField([('group_committees', wagtail.core.blocks.StructBlock([('committee', wagtail.core.blocks.CharBlock(label='Comité')), ('committee_members', wagtail.core.blocks.ListBlock(wagtail.snippets.blocks.SnippetChooserBlock(open_democracy_back.models.contents_models.People), label='Membre'))], label='Comité d’orientation', label_format='{title}'))], blank=True, verbose_name='Membres des Comités - contenu'),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='who_committee_sub_block_title',
            field=models.CharField(blank=True, help_text="Si ce champ est vide le bloc ne s'affichera pas", max_length=68, verbose_name='Comité d’orientation - titre'),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='who_crew_sub_block_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Logo Démocratie Ouverte'),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='who_crew_sub_block_peoples',
            field=models.ManyToManyField(related_name='crew', to='open_democracy_back.People', verbose_name='Membres de Démocratie Ouverte'),
        ),
    ]
