# Generated by Django 3.2.11 on 2022-02-21 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0011_auto_20220221_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionfilter',
            name='conditional_profile_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions_that_depend_on_me', to='open_democracy_back.profiletype', verbose_name='Filtre par type de profile'),
        ),
        migrations.AddField(
            model_name='questionfilter',
            name='profile_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='definitions', to='open_democracy_back.question'),
        ),
        migrations.AlterField(
            model_name='questionfilter',
            name='conditional_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions_that_depend_on_me', to='open_democracy_back.question', verbose_name='Filtre par question'),
        ),
        migrations.AlterField(
            model_name='questionfilter',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_filters', to='open_democracy_back.question'),
        ),
        migrations.DeleteModel(
            name='QuestionFilterByProfileType',
        ),
    ]
