# Generated by Django 3.2.13 on 2022-07-20 07:52

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import open_democracy_back.models.contents_models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.search.index
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('open_democracy_back', '0011_auto_20220713_0831'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Nom')),
                ('job_title', models.CharField(max_length=136, verbose_name='Intitulé du poste')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Personne',
                'verbose_name_plural': 'Personnes',
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='who_committee_sub_block_data',
            field=wagtail.core.fields.StreamField([('group_committees', wagtail.core.blocks.StructBlock([('committee', wagtail.core.blocks.CharBlock(label='Nom')), ('committee_members', wagtail.core.blocks.ListBlock(wagtail.snippets.blocks.SnippetChooserBlock(open_democracy_back.models.contents_models.Person), label='Membre'))], label='Groupe du Comité d’orientation', label_format='{title}'))], blank=True, verbose_name='Membres du Comité - contenu'),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='who_committee_sub_block_description',
            field=wagtail.core.fields.RichTextField(blank=True, default='', verbose_name='Le Comité d’orientation - description'),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='who_committee_sub_block_title',
            field=models.CharField(blank=True, help_text="Si ce champ est vide le bloc ne s'affichera pas", max_length=68, verbose_name='Le Comité d’orientation - titre'),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='who_crew_sub_block_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Logo Démocratie Ouverte'),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='who_crew_sub_block_title',
            field=models.CharField(blank=True, help_text="Si ce champ est vide le bloc ne s'affichera pas", max_length=68, verbose_name='Equipe Démocratie Ouverte - titre'),
        ),
        migrations.CreateModel(
            name='ProjectPagePerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='who_crew_sub_block_members', to='open_democracy_back.projectpage')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='open_democracy_back.person', verbose_name='Membre')),
            ],
            options={
                'unique_together': {('page', 'person')},
            },
        ),
    ]
