# Generated by Django 3.2.12 on 2022-07-21 16:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0011_auto_20220713_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentresponse',
            name='percentage_response',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='participationresponse',
            name='percentage_response',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
