# Generated by Django 3.2.11 on 2022-07-18 06:55

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


def delete_pages(apps, _):
    EvaluationInitPage = apps.get_model("open_democracy_back", "EvaluationInitPage")
    EvaluationIntroPage = apps.get_model("open_democracy_back", "EvaluationIntroPage")
    EvaluationInitPage.objects.all().delete()
    EvaluationIntroPage.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailforms", "0004_add_verbose_name_plural"),
        ("wagtailcore", "0066_collection_management_permissions"),
        ("wagtailredirects", "0007_add_autocreate_fields"),
        ("open_democracy_back", "0011_auto_20220713_0831"),
    ]

    operations = [
        migrations.RunPython(delete_pages),
        migrations.CreateModel(
            name="EvaluationInitiationPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "search_assessment_title",
                    models.CharField(max_length=255, verbose_name="title"),
                ),
                (
                    "search_assessment_description",
                    models.TextField(
                        blank=True, default="", verbose_name="Description"
                    ),
                ),
                (
                    "consent_title",
                    models.CharField(default="", max_length=255, verbose_name="Titre"),
                ),
                (
                    "consent_description",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Description",
                    ),
                ),
                (
                    "consent_checkbox",
                    wagtail.core.fields.RichTextField(
                        default="", verbose_name="Text de la case à cocher"
                    ),
                ),
                (
                    "no_assessment_title",
                    models.CharField(default="", max_length=255, verbose_name="Titre"),
                ),
                (
                    "no_assessment_description",
                    models.TextField(
                        blank=True, default="", verbose_name="Description"
                    ),
                ),
                (
                    "one_assessment_with_expert_title",
                    models.CharField(default="", max_length=255, verbose_name="Titre"),
                ),
                (
                    "one_assessment_with_expert_description",
                    models.TextField(
                        blank=True, default="", verbose_name="Description"
                    ),
                ),
                (
                    "one_participation_assessment_title",
                    models.CharField(default="", max_length=255, verbose_name="Titre"),
                ),
                (
                    "one_participation_assessment_description",
                    models.TextField(
                        blank=True, default="", verbose_name="Description"
                    ),
                ),
                (
                    "create_quick_assessment_title",
                    models.CharField(default="", max_length=255, verbose_name="Titre"),
                ),
                (
                    "create_quick_assessment_description",
                    models.TextField(
                        blank=True, default="", verbose_name="Description"
                    ),
                ),
                (
                    "create_participation_assessment_title",
                    models.CharField(default="", max_length=255, verbose_name="Titre"),
                ),
                (
                    "create_participation_assessment_description",
                    models.TextField(
                        blank=True, default="", verbose_name="Description"
                    ),
                ),
                (
                    "create_assessment_with_expert_title",
                    models.CharField(default="", max_length=255, verbose_name="Titre"),
                ),
                (
                    "create_assessment_with_expert_description",
                    models.TextField(
                        blank=True, default="", verbose_name="Description"
                    ),
                ),
                (
                    "initiator_name_question",
                    models.CharField(
                        default="",
                        max_length=255,
                        verbose_name="Enoncé de la question sur le nom de l'initateur qui sera affiché publiquement",
                    ),
                ),
                (
                    "initiator_name_description",
                    models.TextField(
                        blank=True,
                        default="",
                        verbose_name="Description de la question sur le nom de l'initateur qui sera affiché publiquement",
                    ),
                ),
                (
                    "representativity_title",
                    models.TextField(
                        default="",
                        help_text="Correspond à la partie où seront posées les questions sur les seuils d'acceptabilité de la représentativité",
                        verbose_name="Titre pour les questions sur les seuils d'acceptabilité de la représentativité",
                    ),
                ),
                (
                    "representativity_description",
                    wagtail.core.fields.RichTextField(
                        blank=True,
                        default="",
                        help_text="Permet à la personne de mieux comprendre les questions sur les représentativités, et lui donne des éléments de réponse",
                        verbose_name="Description de la question sur la limite de représentativité",
                    ),
                ),
                (
                    "initialization_validation_title",
                    models.CharField(default="", max_length=255, verbose_name="Titre"),
                ),
                (
                    "initialization_validation_description",
                    wagtail.core.fields.RichTextField(
                        blank=True,
                        default="",
                        help_text="S'affichera une fois l'initialisation de l'évaluation terminée",
                        verbose_name="Texte de validation de l'initialisation d'une évaluation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lancement d'une évaluation",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.RemoveField(
            model_name="evaluationintropage",
            name="page_ptr",
        ),
        migrations.DeleteModel(
            name="EvaluationInitPage",
        ),
        migrations.DeleteModel(
            name="EvaluationIntroPage",
        ),
    ]
