# Generated by Django 3.2.11 on 2022-07-12 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0011_assessment_published_results'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='published_results',
        ),
        migrations.AddField(
            model_name='resultspage',
            name='tag_line_no_results',
            field=models.CharField(default='', max_length=510, verbose_name='Consigne si aucun résultat publié'),
        ),
        migrations.AlterField(
            model_name='assessmentrepresentativity',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representativities', to='open_democracy_back.assessment'),
        ),
        migrations.AlterField(
            model_name='assessmentrepresentativity',
            name='representativity_criteria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representativities', to='open_democracy_back.representativitycriteria'),
        ),
        migrations.AlterField(
            model_name='resultspage',
            name='tag_line',
            field=models.CharField(default='', max_length=510, verbose_name='Consigne'),
        ),
    ]
