# Generated by Django 3.2.11 on 2022-07-10 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0011_auto_20220710_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pillar',
            name='score_1',
        ),
        migrations.RemoveField(
            model_name='pillar',
            name='score_2',
        ),
        migrations.RemoveField(
            model_name='pillar',
            name='score_3',
        ),
        migrations.RemoveField(
            model_name='pillar',
            name='score_4',
        ),
        migrations.RemoveField(
            model_name='pillar',
            name='strength_3',
        ),
        migrations.RemoveField(
            model_name='pillar',
            name='strength_4',
        ),
        migrations.RemoveField(
            model_name='pillar',
            name='weakness_1',
        ),
        migrations.RemoveField(
            model_name='pillar',
            name='weakness_2',
        ),
        migrations.AddField(
            model_name='criteria',
            name='strength_3',
            field=models.TextField(blank=True, default='', help_text='Point fort relevé pour une évaluation si le calcul de son score est de 3', verbose_name='Point fort'),
        ),
        migrations.AddField(
            model_name='criteria',
            name='strength_4',
            field=models.TextField(blank=True, default='', help_text='Point fort relevé pour une évaluation si le calcul de son score est de 4', verbose_name='Point fort'),
        ),
        migrations.AddField(
            model_name='criteria',
            name='weakness_1',
            field=models.TextField(blank=True, default='', help_text='Point faible relevé pour une évaluation si le calcul de son score est de 1', verbose_name='Point faible'),
        ),
        migrations.AddField(
            model_name='criteria',
            name='weakness_2',
            field=models.TextField(blank=True, default='', help_text='Point faible relevé pour une évaluation si le calcul de son score est de 2', verbose_name='Point faible'),
        ),
    ]
