# Generated by Django 3.2.11 on 2022-03-15 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0011_auto_20220315_0828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='epci',
            name='municipalities',
        ),
    ]
