# Generated by Django 3.2.11 on 2022-07-12 15:16

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0012_auto_20220712_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultspage',
            name='introduction',
            field=wagtail.core.fields.RichTextField(blank=True, default='', verbose_name='Introduction'),
        ),
    ]
