# Generated by Django 3.2.11 on 2022-07-18 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0012_auto_20220718_0655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluationinitiationpage',
            name='consent_checkbox',
        ),
        migrations.AddField(
            model_name='evaluationinitiationpage',
            name='add_expert_button_no',
            field=models.CharField(default='', max_length=68, verbose_name="Ajout d'un expert - Bouton NON"),
        ),
        migrations.AddField(
            model_name='evaluationinitiationpage',
            name='add_expert_button_yes',
            field=models.CharField(default='', max_length=68, verbose_name="Ajout d'un expert - Bouton OUI"),
        ),
        migrations.AddField(
            model_name='evaluationinitiationpage',
            name='add_expert_description',
            field=models.TextField(blank=True, default='', verbose_name="Ajout d'un expert - Description"),
        ),
        migrations.AddField(
            model_name='evaluationinitiationpage',
            name='add_expert_title',
            field=models.CharField(default='', max_length=255, verbose_name="Ajout d'un expert - Titre"),
        ),
        migrations.AddField(
            model_name='evaluationinitiationpage',
            name='choose_expert_text',
            field=models.CharField(default='', max_length=255, verbose_name='Choisir un expert dans la liste'),
        ),
        migrations.AddField(
            model_name='evaluationinitiationpage',
            name='if_no_expert_text',
            field=models.CharField(default='', max_length=255, verbose_name="Si il n'y a pas mon expert, contactez-nous"),
        ),
    ]
