# Generated by Django 3.2.13 on 2022-07-12 14:22

from django.db import migrations
import open_democracy_back.models.contents_models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0012_auto_20220712_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectpage',
            name='who_crew_sub_block_peoples',
        ),
        migrations.AddField(
            model_name='projectpage',
            name='who_crew_sub_block_peoples',
            field=wagtail.core.fields.StreamField([('crew_members', wagtail.core.blocks.ListBlock(wagtail.snippets.blocks.SnippetChooserBlock(open_democracy_back.models.contents_models.People), label='Membres'))], blank=True, verbose_name='Membres de Démocratie Ouverte - contenu'),
        ),
    ]
