# Generated by Django 3.2.11 on 2022-07-11 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0012_auto_20220710_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criteria',
            name='weakness_1',
        ),
        migrations.RemoveField(
            model_name='criteria',
            name='weakness_2',
        ),
        migrations.RemoveField(
            model_name='marker',
            name='weakness_1',
        ),
        migrations.RemoveField(
            model_name='marker',
            name='weakness_2',
        ),
        migrations.AddField(
            model_name='criteria',
            name='improvement_1',
            field=models.TextField(blank=True, default='', help_text="Point d'amélioration relevé pour une évaluation si le calcul de son score est de 1", verbose_name="Point d'amélioration 1"),
        ),
        migrations.AddField(
            model_name='criteria',
            name='improvement_2',
            field=models.TextField(blank=True, default='', help_text="Point d'amélioration relevé pour une évaluation si le calcul de son score est de 2", verbose_name="Point d'amélioration 2"),
        ),
        migrations.AddField(
            model_name='marker',
            name='improvement_1',
            field=models.TextField(blank=True, default='', help_text="Point d'amélioration relevé pour une évaluation si le calcul de son score est de 1", verbose_name="Point d'amélioration 1"),
        ),
        migrations.AddField(
            model_name='marker',
            name='improvement_2',
            field=models.TextField(blank=True, default='', help_text="Point d'amélioration relevé pour une évaluation si le calcul de son score est de 2", verbose_name="Point d'amélioration 2"),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='strength_3',
            field=models.TextField(blank=True, default='', help_text='Point fort relevé pour une évaluation si le calcul de son score est de 3', verbose_name='Point fort 3'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='strength_4',
            field=models.TextField(blank=True, default='', help_text='Point fort relevé pour une évaluation si le calcul de son score est de 4', verbose_name='Point fort 4'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='strength_3',
            field=models.TextField(blank=True, default='', help_text='Point fort relevé pour une évaluation si le calcul de son score est de 3', verbose_name='Point fort 3'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='strength_4',
            field=models.TextField(blank=True, default='', help_text='Point fort relevé pour une évaluation si le calcul de son score est de 4', verbose_name='Point fort 4'),
        ),
    ]
