# Generated by Django 3.2.11 on 2022-03-17 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0012_remove_epci_municipalities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='epci',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='open_democracy_back.epci', verbose_name='Intercommunalité'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='municipality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='open_democracy_back.municipality', verbose_name='Commune'),
        ),
    ]
