# Generated by Django 3.2.11 on 2022-02-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0013_auto_20220221_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='intersection_operator',
        ),
        migrations.AddField(
            model_name='profiletype',
            name='rules_intersection_operator',
            field=models.CharField(blank=True, choices=[('and', 'et'), ('or', 'ou')], max_length=8),
        ),
        migrations.AddField(
            model_name='question',
            name='rules_intersection_operator',
            field=models.CharField(blank=True, choices=[('and', 'et'), ('or', 'ou')], max_length=8),
        ),
    ]
