# Generated by Django 3.2.11 on 2022-07-18 13:51

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0013_auto_20220718_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationinitiationpage',
            name='init_description',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='evaluationinitiationpage',
            name='init_title',
            field=models.CharField(default='', max_length=255, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='evaluationinitiationpage',
            name='initialization_validation_description',
            field=wagtail.core.fields.RichTextField(blank=True, default='', verbose_name='Description - page de validation'),
        ),
        migrations.AlterField(
            model_name='evaluationinitiationpage',
            name='initialization_validation_title',
            field=models.CharField(default='', help_text="S'affichera une fois l'initialisation de l'évaluation terminée", max_length=255, verbose_name='Titre - page de validation'),
        ),
        migrations.AlterField(
            model_name='evaluationinitiationpage',
            name='representativity_description',
            field=wagtail.core.fields.RichTextField(blank=True, default='', help_text='Permet à la personne de mieux comprendre les questions sur les représentativités, et lui donne des éléments de réponse', verbose_name="Description - page des seuils d'acceptabilité de la représentativité"),
        ),
        migrations.AlterField(
            model_name='evaluationinitiationpage',
            name='representativity_title',
            field=models.TextField(default='', help_text="Correspond à la partie où seront posées les questions sur les seuils d'acceptabilité de la représentativité", verbose_name="Titre - page des seuils d'acceptabilité de la représentativité"),
        ),
    ]
