# Generated by Django 3.2.13 on 2022-07-12 14:49

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0013_auto_20220712_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPagePeople',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_page', to='open_democracy_back.projectpage')),
                ('peoples', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peoples', to='open_democracy_back.people')),
            ],
            options={
                'unique_together': {('page', 'peoples')},
            },
        ),
    ]
