# Generated by Django 3.2.11 on 2022-07-12 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0013_alter_resultspage_introduction'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepresentativityCriteriaRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ignore_for_acceptability_threshold', models.BooleanField(default=False, help_text='Ex: binaire pour la parité', verbose_name="Ne pas compter pour le seuil d'acceptabilité minimal")),
                ('hide_in_assessment_representativity', models.BooleanField(default=False, verbose_name='Ne pas afficher dans le tableau de représentativité')),
                ('representativity_criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='open_democracy_back.representativitycriteria')),
                ('response_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representativitycriteriarule_that_depend_on_me', to='open_democracy_back.responsechoice', verbose_name='Réponse')),
            ],
        ),
    ]
