# Generated by Django 3.2.11 on 2022-03-17 14:29

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('open_democracy_back', '0013_auto_20220317_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationIntroPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduction', models.TextField(default='')),
                ('data_consent', wagtail.core.fields.RichTextField(default='', help_text='Demande de consentement à conserver les données personnelles demandées, RGPD', verbose_name='Consentement sur les données personnelles')),
            ],
            options={
                'verbose_name': "Intro à l'évaluation",
            },
            bases=('wagtailcore.page',),
        ),
    ]
