# Generated by Django 3.2.11 on 2022-07-20 21:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('open_democracy_back', '0013_auto_20220720_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='experts',
            field=models.ManyToManyField(blank=True, help_text="Pour ajouter un expert à la liste il faut créer / modifier l'utilisateur correspondant, aller dans l'onglet rôles et cocher la case Experts", limit_choices_to={'groups__name': 'Experts'}, related_name='assessments', to=settings.AUTH_USER_MODEL, verbose_name='Experts'),
        ),
    ]
