# Generated by Django 3.2.12 on 2022-03-21 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0014_evaluationintropage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epci',
            name='code',
            field=models.CharField(max_length=100, verbose_name='Code siren'),
        ),
        migrations.AlterField(
            model_name='municipalityorderbyepci',
            name='municipality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='open_democracy_back.municipality', verbose_name='Commune'),
        ),
    ]
