# Generated by Django 3.2.12 on 2022-03-21 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0014_evaluationintropage'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsechoice',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Texte précisant la réponse (définition, exemple, reformulation).', null=True, verbose_name='Description de la réponse'),
        ),
    ]
