# Generated by Django 3.2.11 on 2022-07-13 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0014_representativitycriteriarule'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='representativitycriteriarule',
            unique_together={('representativity_criteria', 'response_choice')},
        ),
    ]
