# Generated by Django 3.2.11 on 2022-02-23 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0014_auto_20220223_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiletype',
            name='rules_intersection_operator',
            field=models.CharField(choices=[('and', 'et'), ('or', 'ou')], default='and', max_length=8),
        ),
        migrations.AlterField(
            model_name='question',
            name='rules_intersection_operator',
            field=models.CharField(choices=[('and', 'et'), ('or', 'ou')], default='and', max_length=8),
        ),
    ]
