# Generated by Django 3.2.11 on 2022-07-20 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0014_auto_20220718_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='public_initiator',
        ),
        migrations.AlterField(
            model_name='assessment',
            name='initialized_to_the_name_of',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Initialisé au nom de'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='initiator_type',
            field=models.CharField(blank=True, choices=[('collectivity', 'La collectivité'), ('association', 'Une association'), ('individual', 'Un particulier'), ('other', 'Autre')], max_length=32, null=True),
        ),
    ]
