# Generated by Django 3.2.13 on 2022-07-12 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0014_projectpagepeople'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpagepeople',
            name='peoples',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peoples', to='open_democracy_back.people', verbose_name='Membre'),
        ),
    ]
