# Generated by Django 3.2.11 on 2022-02-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0015_auto_20220223_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='numerical_operator',
            field=models.CharField(blank=True, choices=[('<', '<'), ('>', '>'), ('<=', '<='), ('>=', '>='), ('!=', '!='), ('=', '=')], max_length=8, null=True),
        ),
    ]
