# Generated by Django 3.2.11 on 2022-07-20 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0015_auto_20220720_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationinitiationpage',
            name='must_be_connected_to_create_description',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='evaluationinitiationpage',
            name='must_be_connected_to_create_title',
            field=models.CharField(default='', max_length=255, verbose_name='Titre'),
        ),
    ]
