# Generated by Django 3.2.11 on 2022-03-22 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0015_auto_20220321_0756'),
        ('open_democracy_back', '0015_responsechoice_description'),
    ]

    operations = [
    ]
