# Generated by Django 3.2.13 on 2022-07-12 14:55

from django.db import migrations, models
import open_democracy_back.models.contents_models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0015_alter_projectpagepeople_peoples'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpage',
            name='who_committee_sub_block_data',
            field=wagtail.core.fields.StreamField([('group_committees', wagtail.core.blocks.StructBlock([('committee', wagtail.core.blocks.CharBlock(label='Nom')), ('committee_members', wagtail.core.blocks.ListBlock(wagtail.snippets.blocks.SnippetChooserBlock(open_democracy_back.models.contents_models.People), label='Membre'))], label='Groupe du Comité d’orientation', label_format='{title}'))], blank=True, verbose_name='Membres du Comité - contenu'),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='who_committee_sub_block_description',
            field=wagtail.core.fields.RichTextField(blank=True, default='', verbose_name='Le Comité d’orientation - description'),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='who_committee_sub_block_title',
            field=models.CharField(blank=True, help_text="Si ce champ est vide le bloc ne s'affichera pas", max_length=68, verbose_name='Le Comité d’orientation - titre'),
        ),
    ]
