# Generated by Django 3.2.11 on 2022-07-26 18:54

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('open_democracy_back', '0015_auto_20220721_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaluationinitiationpage',
            old_name='consent_title',
            new_name='cgu_consent_title',
        ),
        migrations.RenameField(
            model_name='evaluationinitiationpage',
            old_name='consent_description',
            new_name='cgu_consent_description_loggedin',
        ),
        migrations.AlterField(
            model_name='evaluationinitiationpage',
            name='cgu_consent_description_loggedin',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Description pour un utilisateur connecté'),
        ),

        migrations.AddField(
            model_name='assessment',
            name='conditions_of_sale_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assessment',
            name='initiator_usage_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evaluationinitiationpage',
            name='cgu_consent_description_loggedout',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Description pour un utilisateur NON connecté'),
        ),
        migrations.AddField(
            model_name='evaluationinitiationpage',
            name='cgv_consent_description',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='evaluationinitiationpage',
            name='cgv_consent_title',
            field=models.CharField(default='', max_length=255, verbose_name='Titre'),
        ),
        migrations.AddField(
            model_name='evaluationinitiationpage',
            name='royalty_description',
            field=models.TextField(blank=True, default='', verbose_name="Texte sur redevance d'utilisation"),
        ),
        migrations.AlterField(
            model_name='evaluationinitiationpage',
            name='create_assessment_with_expert_description',
            field=wagtail.fields.RichTextField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='evaluationinitiationpage',
            name='create_participation_assessment_description',
            field=wagtail.fields.RichTextField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='evaluationinitiationpage',
            name='create_quick_assessment_description',
            field=wagtail.fields.RichTextField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='evaluationinitiationpage',
            name='init_description',
            field=wagtail.fields.RichTextField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='evaluationinitiationpage',
            name='no_assessment_description',
            field=wagtail.fields.RichTextField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='evaluationinitiationpage',
            name='one_assessment_with_expert_description',
            field=wagtail.fields.RichTextField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='evaluationinitiationpage',
            name='one_participation_assessment_description',
            field=wagtail.fields.RichTextField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='evaluationinitiationpage',
            name='one_quick_assessment_description',
            field=wagtail.fields.RichTextField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.CreateModel(
            name='StructureSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Adresse mail de contact')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Paramètre de la structure',
            },
        ),
    ]
