# Generated by Django 3.2.11 on 2022-07-13 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0015_alter_representativitycriteriarule_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representativitycriteriarule',
            name='response_choice',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='representativity_criteria_rule', to='open_democracy_back.responsechoice', verbose_name='Réponse'),
        ),
    ]
