# Generated by Django 3.2.11 on 2022-03-22 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0015_responsechoice_description'),
        ('open_democracy_back', '0016_closedwithrankingresponse_participant_response'),
    ]

    operations = [
    ]
