# Generated by Django 3.2.11 on 2022-07-27 12:49

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0016_auto_20220726_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationinitiationpage',
            name='objective_questions_description',
            field=wagtail.fields.RichTextField(blank=True, default='', verbose_name='Description - Répondre aux questions objectives'),
        ),
        migrations.AddField(
            model_name='evaluationinitiationpage',
            name='objective_questions_title',
            field=models.CharField(default='', max_length=255, verbose_name='Titre - Répondre aux questions objectives'),
        ),
        migrations.AddField(
            model_name='evaluationquestionnairepage',
            name='end_of_profiling_description',
            field=wagtail.fields.RichTextField(default='', help_text="Expliquer qu'il ne sera pas possible de revenir en arrière, puisque les questions du questionnaire dépendent du profilage", verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='evaluationquestionnairepage',
            name='end_of_profiling_title',
            field=models.CharField(default='', max_length=128, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='evaluationquestionnairepage',
            name='role_question_description',
            field=wagtail.fields.RichTextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
