# Generated by Django 3.2.11 on 2022-02-24 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0016_alter_rule_numerical_operator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='profile_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='definitions', to='open_democracy_back.profiletype'),
        ),
    ]
