# Generated by Django 3.2.11 on 2022-07-20 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0016_auto_20220720_0707'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationinitiationpage',
            name='one_quick_assessment_description',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='evaluationinitiationpage',
            name='one_quick_assessment_title',
            field=models.CharField(default='', max_length=255, verbose_name='Titre'),
        ),
    ]
