# Generated by Django 3.2.11 on 2022-07-13 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0016_alter_representativitycriteriarule_response_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='representativitycriteriarule',
            name='hide_in_assessment_representativity',
        ),
        migrations.AddField(
            model_name='representativitycriteriarule',
            name='totally_ignore',
            field=models.BooleanField(default=False, verbose_name='Ignorer totalement'),
        ),
    ]
