# Generated by Django 3.2.11 on 2022-07-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0016_structuresettings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaluationinitiationpage',
            old_name='consent_description',
            new_name='consent_description_loggedin',
        ),
        migrations.AlterField(
            model_name='evaluationinitiationpage',
            name='consent_description_loggedin',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Description pour un utilisateur connecté'),
        ),
        migrations.AddField(
            model_name='evaluationinitiationpage',
            name='consent_description_loggedout',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Description pour un utilisateur NON connecté'),
        ),
    ]
