# Generated by Django 3.2.11 on 2022-03-22 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('open_democracy_back', '0016_merge_20220322_0949'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent', models.BooleanField(default=False)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='open_democracy_back.assessment')),
                ('profiles', models.ManyToManyField(related_name='participations', to='open_democracy_back.ProfileType')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participations', to='open_democracy_back.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'assessment')},
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boolean_response', models.BooleanField(blank=True, null=True)),
                ('numerical_response', models.IntegerField(blank=True, null=True)),
                ('closed_with_scale_response', models.IntegerField(blank=True, null=True)),
                ('multiple_choice_response', models.ManyToManyField(to='open_democracy_back.ResponseChoice')),
                ('participation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='open_democracy_back.participation')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='open_democracy_back.question')),
                ('unique_choice_response', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', to='open_democracy_back.responsechoice')),
            ],
        ),
        migrations.CreateModel(
            name='ClosedWithRankingResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closed_with_ranking_responses_ordered', to='open_democracy_back.response')),
                ('response_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='open_democracy_back.responsechoice')),
            ],
            options={
                'order_with_respect_to': 'response',
            },
        ),
    ]
