# Generated by Django 3.2.11 on 2022-03-22 10:16

from django.db import migrations, models


def addOrderToPillars(apps, _):
    Pillar = apps.get_model("open_democracy_back", "Pillar")
    for index, name in enumerate(
        [
            "représentation",
            "transparence",
            "participation",
            "coopération",
        ]
    ):
        pillar = Pillar.objects.filter(name=name).get()
        pillar.order = index
        pillar.save()


def removeOrderToPillars(apps, _):
    apps.get_model("open_democracy_back", "Pillar").objects.all().update(order=1)


class Migration(migrations.Migration):

    dependencies = [
        (
            "open_democracy_back",
            "0017_closedwithrankingresponse_participation_response",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pillar",
            options={
                "ordering": ["order"],
                "verbose_name": "1. Pilier",
                "verbose_name_plural": "1. Piliers",
            },
        ),
        migrations.AddField(
            model_name="pillar",
            name="order",
            field=models.IntegerField(
                default="1",
                help_text="Permet de ranger dans l'ordre voulu les piliers",
                verbose_name="Ordre",
            ),
        ),
        migrations.RunPython(addOrderToPillars, removeOrderToPillars),
    ]
