# Generated by Django 3.2.11 on 2022-07-26 16:01

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0017_auto_20220726_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationinitiationpage',
            name='create_assessment_with_expert_description',
            field=wagtail.core.fields.RichTextField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='evaluationinitiationpage',
            name='create_participation_assessment_description',
            field=wagtail.core.fields.RichTextField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='evaluationinitiationpage',
            name='create_quick_assessment_description',
            field=wagtail.core.fields.RichTextField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='evaluationinitiationpage',
            name='init_description',
            field=wagtail.core.fields.RichTextField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='evaluationinitiationpage',
            name='no_assessment_description',
            field=wagtail.core.fields.RichTextField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='evaluationinitiationpage',
            name='one_assessment_with_expert_description',
            field=wagtail.core.fields.RichTextField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='evaluationinitiationpage',
            name='one_participation_assessment_description',
            field=wagtail.core.fields.RichTextField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='evaluationinitiationpage',
            name='one_quick_assessment_description',
            field=wagtail.core.fields.RichTextField(blank=True, default='', verbose_name='Description'),
        ),
    ]
