# Generated by Django 3.2.11 on 2022-07-27 17:29

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0017_auto_20220727_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='representativitycriteria',
            name='explanation',
            field=wagtail.core.fields.RichTextField(blank=True, default='', help_text="L'explication doit aider l'utilisateur à savoir quel pourcentage indiquer et expliciter le pourcentage renseigné par défault", verbose_name='Explication'),
        ),
    ]
