# Generated by Django 3.2.11 on 2022-07-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0018_auto_20220726_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaluationinitiationpage',
            old_name='consent_description_loggedin',
            new_name='cgu_consent_description_loggedin',
        ),
        migrations.RenameField(
            model_name='evaluationinitiationpage',
            old_name='consent_description_loggedout',
            new_name='cgu_consent_description_loggedout',
        ),
        migrations.RenameField(
            model_name='evaluationinitiationpage',
            old_name='consent_title',
            new_name='cgu_consent_title',
        ),
        migrations.AddField(
            model_name='assessment',
            name='conditions_of_sale_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evaluationinitiationpage',
            name='cgv_consent_description',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='evaluationinitiationpage',
            name='cgv_consent_title',
            field=models.CharField(default='', max_length=255, verbose_name='Titre'),
        ),
        migrations.AddField(
            model_name='evaluationinitiationpage',
            name='royalty_description',
            field=models.TextField(blank=True, default='', verbose_name="Texte sur redevance d'utilisation"),
        ),
    ]
