# Generated by Django 3.2.11 on 2022-03-22 17:14

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0018_auto_20220322_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='resources',
        ),
        migrations.AddField(
            model_name='question',
            name='sources',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Sources'),
        ),
        migrations.AddField(
            model_name='question',
            name='to_go_further',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Pour aller plus loin '),
        ),
        migrations.AlterField(
            model_name='question',
            name='use_case',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Exemples inspirants'),
        ),
    ]
