# Generated by Django 3.2.11 on 2022-03-22 10:39

from django.db import migrations, transaction
from django.contrib.contenttypes.models import ContentType
from wagtail.core.models import Page, Site


def addPages(apps, _):
    HomePage = apps.get_model("open_democracy_back", "HomePage")
    ReferentialPage = apps.get_model("open_democracy_back", "ReferentialPage")
    EvaluationIntroPage = apps.get_model("open_democracy_back", "EvaluationIntroPage")

    if not HomePage.objects.filter(locale__language_code="fr").count():
        with transaction.atomic():
            try:
                default_home = Page.objects.filter(
                    title="Welcome to your new Wagtail site!"
                )[0]
                default_home.slug = "home-old"
                default_home.save_revision().publish()
                default_home.save()
            except:
                pass

            home_page = HomePage(
                title="Bienvenue sur DemoMeter",
                introduction="Plateforme d’évaluation participative de la démocratie locale.",
                slug="home",
                content_type=ContentType.objects.filter(model="homepage").get(),
            )
            breakpoint()

            # Set Home Page as child of root
            root_page = Page.objects.get(id=1).specific
            root_page.add_child(instance=home_page)

            # Save and publish Home Page
            home_page.save_revision().publish()
            home_page.save()

            # Set Home Page as root page for Site
            site = Site.objects.get(id=1)
            site.root_page = home_page
            site.save()
    else:
        home_page = HomePage.objects.filter(locale__language_code="fr").get()
    if not ReferentialPage.objects.filter(locale__language_code="fr").count():
        with transaction.atomic():
            referential_page = ReferentialPage(
                title="Le référentiel",
                introduction="""Notre référentiel se compose de 4 piliers,
                composés de plusieurs marqueurs regroupant plusieurs critères.
                Chaque critère possède un score allant de 1 à 4.""",
                slug="referentiel",
            )
            home_page.add_child(instance=referential_page)
            referential_page.save_revision().publish()
            referential_page.save()
    if not EvaluationIntroPage.objects.filter(locale__language_code="fr").count():
        with transaction.atomic():
            evaluation_intro_page = EvaluationIntroPage(
                title="Introduction",
                introduction="""En créant un compte, vous participez à l’évaluation en partageant vos réponses avec les autres.
                Avec ou sans compte, les informations issues de ce questionnaire seront stockées et anonymisées.
                [Listes des acteurs] pourront ensuite les étudier si vous y consentez en cochant la case ci-dessous.""",
                slug="evaluation",
            )
            home_page.add_child(instance=evaluation_intro_page)
            evaluation_intro_page.save_revision().publish()
            evaluation_intro_page.save()


def removePages(_, __):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("open_democracy_back", "0018_auto_20220322_1016"),
    ]

    operations = [
        migrations.RunPython(addPages, removePages),
    ]
