# Generated by Django 3.2.12 on 2022-02-24 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0018_thematictag'),
    ]

    operations = [
        migrations.AddField(
            model_name='criteria',
            name='thematic_tags',
            field=models.ManyToManyField(blank=True, to='open_democracy_back.ThematicTag', verbose_name='Thématiques'),
        ),
    ]
