# Generated by Django 3.2.11 on 2022-07-28 15:17

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('open_democracy_back', '0018_representativitycriteria_explanation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimatorPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('list_workshops_title', models.CharField(max_length=128, verbose_name='Titre')),
                ('list_workshop_intro', models.TextField(default='', verbose_name='Introduction')),
                ('close_workshop_validation', wagtail.core.fields.RichTextField(default='', help_text="Après clôture l'expert ne pourra plus accéder aux réponses des participants et donc ne pourra plus les modifier, leurs réponses seront alors pris en compte pour le calcul des résultats", verbose_name="Explication du la clôture d'un workshop")),
                ('add_participants_title', models.CharField(max_length=128, verbose_name='Titre')),
                ('add_participants_intro', models.TextField(default='', verbose_name='Introduction')),
                ('responses_title', models.CharField(max_length=128, verbose_name='Titre')),
                ('responses_intro', models.TextField(default='', verbose_name='Introduction')),
            ],
            options={
                'verbose_name': 'Espace Expert',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='question',
            name='allows_to_explain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='explained_by', to='open_democracy_back.question', verbose_name="Permet d'expliciter une autre question"),
        ),
    ]
