# Generated by Django 3.2.11 on 2022-07-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0019_auto_20220726_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='initiator_usage_consent',
            field=models.BooleanField(default=False),
        ),
    ]
