# Generated by Django 3.2.12 on 2022-02-24 14:33

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0019_criteria_thematic_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Definition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
                ('explanation', wagtail.core.fields.RichTextField()),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='comments',
            field=wagtail.core.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='legal_frame',
            field=wagtail.core.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='resources',
            field=wagtail.core.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='use_case',
            field=wagtail.core.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='definitions',
            field=models.ManyToManyField(blank=True, to='open_democracy_back.Definition', verbose_name='Défintions'),
        ),
    ]
