# Generated by Django 3.2.11 on 2022-09-01 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0019_auto_20220728_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='external_link',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Lien externe'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='external_link',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Lien externe'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='external_link',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Lien externe'),
        ),
    ]
