# Generated by Django 3.2.11 on 2022-03-23 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('open_democracy_back', '0019_auto_20220322_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='carried_by',
            field=models.ForeignKey(blank=True, help_text="Si l'évaluation est porté par la localité, qui en est responsable", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carried_assessments', to=settings.AUTH_USER_MODEL, verbose_name='Porté par'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de fin'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='initialization_date',
            field=models.DateField(blank=True, help_text="Si il n'y a pas de date d'initialisation, c'est que le début de l'évaluation n'a pas été confirmée", null=True, verbose_name="Date d'initialisation"),
        ),
        migrations.AddField(
            model_name='assessment',
            name='initiated_by',
            field=models.ForeignKey(blank=True, help_text="Si l'évaluation est initié au nom de la localité, quelqu'un peut tout de même être à la source", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_assessments', to=settings.AUTH_USER_MODEL, verbose_name='Initialisé par'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='is_carried_by_locality',
            field=models.BooleanField(default=False, verbose_name='Est porté par la localité ?'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='is_initiated_by_locality',
            field=models.BooleanField(default=False, verbose_name='Est initialisé par la localité ?'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='last_participation_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de dernière participation'),
        ),
        migrations.AlterField(
            model_name='question',
            name='comments',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Indication affichée uniquement pour les administrateurs.', null=True, verbose_name="Commentaires (pour l'interne)"),
        ),
        migrations.AlterField(
            model_name='question',
            name='to_go_further',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Pour aller plus loin'),
        ),
    ]
