# Generated by Django 3.2.11 on 2022-09-12 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0020_auto_20220901_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationinitiationpage',
            name='initialization_validation_call_to_action',
            field=models.CharField(default="Commencer l'évaluation", max_length=32, verbose_name='Call to action - page de validation'),
        ),
        migrations.AddField(
            model_name='evaluationinitiationpage',
            name='objective_questions_call_to_action',
            field=models.CharField(default='Commencer', max_length=32, verbose_name='Call to action - Répondre aux questions objectives'),
        ),
        migrations.AddField(
            model_name='evaluationquestionnairepage',
            name='end_of_profiling_call_to_action',
            field=models.CharField(default='Valider', max_length=32, verbose_name='Call to action'),
        ),
    ]
