# Generated by Django 3.2.12 on 2022-02-24 14:57

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0020_auto_20220224_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='definition',
            name='explanation',
            field=wagtail.core.fields.RichTextField(verbose_name='explication'),
        ),
        migrations.AlterField(
            model_name='definition',
            name='word',
            field=models.CharField(max_length=255, verbose_name='mot'),
        ),
        migrations.AlterField(
            model_name='question',
            name='comments',
            field=wagtail.core.fields.RichTextField(help_text='Indication affichée uniquement pour les administrateurs.', null=True, verbose_name='Commentaires'),
        ),
        migrations.AlterField(
            model_name='question',
            name='legal_frame',
            field=wagtail.core.fields.RichTextField(null=True, verbose_name='Cadre légal'),
        ),
        migrations.AlterField(
            model_name='question',
            name='resources',
            field=wagtail.core.fields.RichTextField(null=True, verbose_name='Ressources'),
        ),
        migrations.AlterField(
            model_name='question',
            name='use_case',
            field=wagtail.core.fields.RichTextField(null=True, verbose_name="Cas d'usage"),
        ),
    ]
