# Generated by Django 3.2.11 on 2022-03-23 17:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0020_auto_20220323_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('category', models.CharField(default='', help_text='Permet de répondre à la même question pour différentes catégories', max_length=64, verbose_name='Categorie')),
            ],
            options={
                'verbose_name': 'Catégorie',
            },
        ),
        migrations.RemoveField(
            model_name='response',
            name='closed_with_scale_response',
        ),
        migrations.AlterField(
            model_name='question',
            name='method',
            field=models.CharField(blank=True, choices=[('quantitative', 'Quantitative'), ('qualitative', 'Qualitative')], max_length=32, verbose_name='Methode'),
        ),
        migrations.AlterField(
            model_name='question',
            name='objectivity',
            field=models.CharField(choices=[('objective', 'Objective'), ('subjective', 'Subjective')], default='subjective', max_length=32, verbose_name='Objective / Subjective'),
        ),
        migrations.CreateModel(
            name='ClosedWithScaleCategoryResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_value', models.IntegerField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='closed_with_scale_category_responses', to='open_democracy_back.category')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closed_with_scale_response_categories', to='open_democracy_back.response')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='question',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='open_democracy_back.question'),
        ),
    ]
