# Generated by Django 3.2.12 on 2022-02-24 16:50

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0021_auto_20220224_1457'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='definition',
            options={'verbose_name': 'Définition', 'verbose_name_plural': 'Définitions'},
        ),
        migrations.RemoveField(
            model_name='question',
            name='definitions',
        ),
        migrations.AddField(
            model_name='question',
            name='roles',
            field=models.ManyToManyField(blank=True, to='open_democracy_back.Role'),
        ),
        migrations.AlterField(
            model_name='question',
            name='comments',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Indication affichée uniquement pour les administrateurs.', null=True, verbose_name='Commentaires'),
        ),
        migrations.AlterField(
            model_name='question',
            name='legal_frame',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Cadre légal'),
        ),
        migrations.AlterField(
            model_name='question',
            name='resources',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Ressources'),
        ),
        migrations.AlterField(
            model_name='question',
            name='use_case',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name="Cas d'usage"),
        ),
        migrations.CreateModel(
            name='QuestionDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='open_democracy_back.definition')),
                ('question', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_definition_ordered', to='open_democracy_back.question')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
