# Generated by Django 3.2.11 on 2022-03-02 14:43

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('open_democracy_back', '0022_auto_20220224_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferentialPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduction', models.CharField(default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Référentiel',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': "Page d'accueil"},
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='body',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='tagline',
        ),
        migrations.AddField(
            model_name='homepage',
            name='introduction',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='marker',
            name='description',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Description pour le référentiel', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='marker',
            name='score_1',
            field=models.TextField(default='', help_text='Description pour le référentiel', verbose_name='Score = 1'),
        ),
        migrations.AddField(
            model_name='marker',
            name='score_2',
            field=models.TextField(default='', help_text='Description pour le référentiel', verbose_name='Score = 2'),
        ),
        migrations.AddField(
            model_name='marker',
            name='score_3',
            field=models.TextField(default='', help_text='Description pour le référentiel', verbose_name='Score = 3'),
        ),
        migrations.AddField(
            model_name='marker',
            name='score_4',
            field=models.TextField(default='', help_text='Description pour le référentiel', verbose_name='Score = 4'),
        ),
        migrations.AddField(
            model_name='pillar',
            name='description',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Description pour le référentiel', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='question',
            name='description',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Texte précisant la question et pourquoi elle est posée.', null=True, verbose_name='Description'),
        ),
    ]
