# Generated by Django 3.2.11 on 2022-03-28 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0022_auto_20220325_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Texte précisant le rôle (définition, exemple, reformulation).', null=True, verbose_name='Description du rôle'),
        ),
    ]
