# Generated by Django 3.2.12 on 2022-09-19 09:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0022_auto_20220914_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criteria',
            name='code',
            field=models.IntegerField(help_text='Correspond au numéro de ce critère dans son marqueur', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='Code'),
        ),
    ]
