# Generated by Django 3.2.11 on 2022-03-31 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0023_role_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='conditional_role',
        ),
        migrations.AlterField(
            model_name='question',
            name='roles',
            field=models.ManyToManyField(blank=True, help_text="Si aucun rôle n'est sélectionné c'est comme si tous l'étaient", to='open_democracy_back.Role', verbose_name='Rôles concernés'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='profile_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='open_democracy_back.profiletype'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='open_democracy_back.question'),
        ),
    ]
