# Generated by Django 3.2.12 on 2022-09-23 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0023_alter_criteria_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledefinition',
            name='conditional_question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiledefinition_that_depend_on_me', to='open_democracy_back.question', verbose_name='Filtre par question'),
        ),
        migrations.AlterField(
            model_name='questionrule',
            name='conditional_question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionrule_that_depend_on_me', to='open_democracy_back.question', verbose_name='Filtre par question'),
        ),
    ]
