# Generated by Django 3.2.11 on 2022-04-01 10:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0024_auto_20220331_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('numerical_operator', models.CharField(blank=True, choices=[('<', '<'), ('>', '>'), ('<=', '<='), ('>=', '>='), ('!=', '!='), ('=', '=')], max_length=8, null=True)),
                ('numerical_value', models.IntegerField(blank=True, null=True)),
                ('boolean_response', models.BooleanField(blank=True, null=True)),
                ('conditional_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiledefinition_that_depend_on_me', to='open_democracy_back.question', verbose_name='Filtre par question')),
                ('profile_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='open_democracy_back.profiletype')),
                ('response_choices', models.ManyToManyField(to='open_democracy_back.ResponseChoice')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('numerical_operator', models.CharField(blank=True, choices=[('<', '<'), ('>', '>'), ('<=', '<='), ('>=', '>='), ('!=', '!='), ('=', '=')], max_length=8, null=True)),
                ('numerical_value', models.IntegerField(blank=True, null=True)),
                ('boolean_response', models.BooleanField(blank=True, null=True)),
                ('conditional_profile_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules_that_depend_on_me', to='open_democracy_back.profiletype', verbose_name='Filtre par type de profile')),
                ('conditional_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionrule_that_depend_on_me', to='open_democracy_back.question', verbose_name='Filtre par question')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='open_democracy_back.question')),
                ('response_choices', models.ManyToManyField(to='open_democracy_back.ResponseChoice')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Rule',
        ),
    ]
