# Generated by Django 3.2.11 on 2022-04-06 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0025_auto_20220401_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionrule',
            name='conditional_profile_type',
        ),
        migrations.AddField(
            model_name='question',
            name='allows_to_explain',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='explained_by', to='open_democracy_back.question', verbose_name="Permet d'expliciter une autre question"),
        ),
        migrations.AddField(
            model_name='question',
            name='max_multiple_choices',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nombre maximal de choix possible'),
        ),
        migrations.AddField(
            model_name='question',
            name='population_lower_bound',
            field=models.IntegerField(blank=True, help_text="Si aucune valeur n'est renseignée, aucune borne inférieur ne sera prise en compte", null=True, verbose_name='Borne inférieure (population min)'),
        ),
        migrations.AddField(
            model_name='question',
            name='population_upper_bound',
            field=models.IntegerField(blank=True, help_text="Si aucune valeur n'est renseignée, aucune borne suppérieur ne sera prise en compte", null=True, verbose_name='Borne suppérieur (population max)'),
        ),
        migrations.AddField(
            model_name='question',
            name='profiles',
            field=models.ManyToManyField(blank=True, related_name='questions_that_depend_on_me', to='open_democracy_back.ProfileType', verbose_name='Profils concernés'),
        ),
    ]
