# Generated by Django 3.2.12 on 2022-10-17 10:30

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0025_auto_20221011_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='referentialpage',
            name='rosette_legend',
            field=wagtail.core.fields.RichTextField(blank=True, default='', verbose_name='Légende du schéma interactif'),
        ),
    ]
