# Generated by Django 3.2.11 on 2022-04-05 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0025_auto_20220401_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionrule',
            name='conditional_profile_type',
        ),
        migrations.AddField(
            model_name='question',
            name='profiles',
            field=models.ManyToManyField(blank=True, related_name='questions_that_depend_on_me', to='open_democracy_back.ProfileType', verbose_name='Profils concernés'),
        ),
    ]
