# Generated by Django 3.2.11 on 2022-04-06 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0026_auto_20220405_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='population_lower_bound',
            field=models.IntegerField(blank=True, help_text="Si aucune valeur n'est renseignée, aucune borne inférieur ne sera prise en compte", null=True, verbose_name='Borne inférieure (population min)'),
        ),
        migrations.AddField(
            model_name='question',
            name='population_upper_bound',
            field=models.IntegerField(blank=True, help_text="Si aucune valeur n'est renseignée, aucune borne suppérieur ne sera prise en compte", null=True, verbose_name='Borne suppérieur (population max)'),
        ),
    ]
