# Generated by Django 3.2.12 on 2022-10-18 10:16

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0026_referentialpage_rosette_legend'),
    ]

    operations = [
        migrations.AddField(
            model_name='referentialpage',
            name='pillar_structure_legend',
            field=wagtail.core.fields.RichTextField(blank=True, default='', verbose_name="Légende du schéma d'arborescence du DémoMètre"),
        ),
    ]
