# Generated by Django 3.2.11 on 2022-04-07 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0027_auto_20220406_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='max',
        ),
        migrations.RemoveField(
            model_name='question',
            name='max_associated_score',
        ),
        migrations.RemoveField(
            model_name='question',
            name='max_label',
        ),
        migrations.RemoveField(
            model_name='question',
            name='min',
        ),
        migrations.RemoveField(
            model_name='question',
            name='min_associated_score',
        ),
        migrations.RemoveField(
            model_name='question',
            name='min_label',
        ),
        migrations.AlterField(
            model_name='responsechoice',
            name='description',
            field=models.TextField(blank=True, default='', help_text="Texte précisant la réponse (définition, exemple, reformulation). Si la question est fermée à échelle la description ne s'affichera pas.", null=True, verbose_name='Description de la réponse'),
        ),
    ]
