# Generated by Django 3.2.11 on 2022-04-12 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0027_auto_20220407_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationintropage',
            name='account_incentive',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='evaluationintropage',
            name='account_incentive_title',
            field=models.CharField(default='', max_length=68),
        ),
    ]
