# Generated by Django 3.2.11 on 2022-04-06 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0027_auto_20220406_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='allows_to_explain',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='explained_by', to='open_democracy_back.question', verbose_name="Permet d'expliciter une autre question"),
        ),
    ]
