# Generated by Django 3.2.11 on 2022-10-27 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('open_democracy_back', '0028_contentpage_importantpages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImportantPages',
            new_name='ImportantPagesSettings',
        ),
    ]
