# Generated by Django 3.2.11 on 2022-04-13 15:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import wagtail.search.index


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0028_auto_20220412_0928'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='response',
            unique_together={('participation', 'question')},
        ),
        migrations.CreateModel(
            name='RepresentativityCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Nom')),
                ('min_rate', models.IntegerField(blank=True, help_text='En dessous de ce taux (%) la publication des résultats est interdite', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Taux (en %) minimum acceptable pour la publication des résultats')),
                ('profiling_question', models.OneToOneField(limit_choices_to={'type': 'unique_choice'}, on_delete=django.db.models.deletion.CASCADE, related_name='representativity_criteria', to='open_democracy_back.profilingquestion', verbose_name='Question de profilage reliée')),
            ],
            options={
                'verbose_name': 'Critère de représentativité',
                'verbose_name_plural': 'Critères de représentativité',
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
    ]
