# Generated by Django 3.2.11 on 2022-04-07 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0028_auto_20220407_0906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='closedwithscalecategoryresponse',
            name='response_value',
        ),
        migrations.AddField(
            model_name='closedwithscalecategoryresponse',
            name='response_choice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='open_democracy_back.responsechoice'),
            preserve_default=False,
        ),
    ]
