# Generated by Django 3.2.11 on 2022-04-06 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0028_question_allows_to_explain'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='max_multiple_choices',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nombre maximal de choix possible'),
        ),
    ]
