# Generated by Django 3.2.11 on 2022-04-15 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0029_evaluationinitpage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaluationinitpage',
            old_name='description',
            new_name='introduction',
        ),
        migrations.AlterField(
            model_name='evaluationinitpage',
            name='public_name_question',
            field=models.TextField(default='', help_text="Question RGPD - La réponse est oui / non - Si l'évaluation est faite au nom d'une association alors c'est le nom de cette association qui sera affichée", verbose_name="Enoncé de la question pour la publication ou non du nom de l'initateur"),
        ),
    ]
