# Generated by Django 3.2.11 on 2022-11-04 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0029_rename_importantpages_importantpagessettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationinitiationpage',
            name='dashboard_description',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='evaluationinitiationpage',
            name='dashboard_title',
            field=models.CharField(default='', max_length=255, verbose_name='Titre'),
        ),
    ]
