# Generated by Django 3.2.11 on 2022-04-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0030_auto_20220422_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationintropage',
            name='account_incentive',
            field=models.CharField(default='', max_length=255, verbose_name='Incitation à la connexion'),
        ),
        migrations.AlterField(
            model_name='evaluationintropage',
            name='account_incentive_title',
            field=models.CharField(default='', max_length=68, verbose_name="Titre pour l'incitation à la connexion"),
        ),
    ]
