# Generated by Django 3.2.11 on 2022-11-04 10:09

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0030_auto_20221104_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationinitiationpage',
            name='dashboard_description',
            field=wagtail.fields.RichTextField(blank=True, default='', verbose_name='Description'),
        ),
    ]
