# Generated by Django 3.2.11 on 2022-04-21 08:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0030_auto_20220415_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationinitpage',
            name='representativity_description',
            field=models.TextField(default='', help_text='Permet à la personne de mieux comprendre la question sur les représentativités, et lui donne des éléments de réponse', verbose_name='Description de la question sur la limite de représentativité'),
        ),
        migrations.AddField(
            model_name='evaluationinitpage',
            name='representativity_question',
            field=models.TextField(default='', help_text='Question sur la représentativité, cette question suivra la partie RGPD', verbose_name='Enoncé de la question sur la limite de représentativité pour la publication des résultats'),
        ),
        migrations.AlterField(
            model_name='evaluationinitpage',
            name='public_name_question',
            field=models.TextField(default='', help_text="Question RGPD - La réponse est oui / non - Si l'évaluation est faite au nom d'une association alors c'est le nom de cette association qui sera affichée", verbose_name="Enoncé de la question sur la publication ou non du nom de l'initateur"),
        ),
        migrations.CreateModel(
            name='AssessmentRepresentativity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acceptability_threshold', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name="Seuil d'acceptabilité")),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representativites', to='open_democracy_back.assessment')),
                ('representativity_criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representativites', to='open_democracy_back.representativitycriteria')),
            ],
        ),
    ]
