# Generated by Django 3.2.11 on 2022-04-21 08:04

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0031_auto_20220421_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationinitpage',
            name='representativity_description',
            field=wagtail.core.fields.RichTextField(default='', help_text='Permet à la personne de mieux comprendre la question sur les représentativités, et lui donne des éléments de réponse', verbose_name='Description de la question sur la limite de représentativité'),
        ),
    ]
