# Generated by Django 3.2.11 on 2022-04-26 08:08

from django.db import migrations, models


def addDotToConcatenatedCode(apps, _):
    Marker = apps.get_model("open_democracy_back", "Marker")
    Criteria = apps.get_model("open_democracy_back", "Criteria")
    QuestionnaireQuestion = apps.get_model(
        "open_democracy_back", "QuestionnaireQuestion"
    )
    markers = Marker.objects.all()
    for marker in markers:
        marker.concatenated_code = (
            marker.pillar.code + "." if marker.pillar else ""
        ) + marker.code
        marker.save()
    criterias = Criteria.objects.all()
    for criteria in criterias:
        criteria.concatenated_code = (
            criteria.marker.concatenated_code + "." if criteria.marker else ""
        ) + criteria.code
        criteria.save()
    questionnaire_questions = QuestionnaireQuestion.objects.all()
    for questionnaire_question in questionnaire_questions:
        questionnaire_question.concatenated_code = (
            questionnaire_question.criteria.concatenated_code + "."
            if questionnaire_question.criteria
            else ""
        ) + questionnaire_question.code
        questionnaire_question.save()


def removeDotToConcatenatedCode(apps, _):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("open_democracy_back", "0031_auto_20220425_1640"),
    ]

    operations = [
        migrations.AlterField(
            model_name="criteria",
            name="concatenated_code",
            field=models.CharField(default="", max_length=8),
        ),
        migrations.AlterField(
            model_name="marker",
            name="concatenated_code",
            field=models.CharField(default="", max_length=5),
        ),
        migrations.AlterField(
            model_name="question",
            name="concatenated_code",
            field=models.CharField(default="", max_length=11),
        ),
        migrations.RunPython(addDotToConcatenatedCode, removeDotToConcatenatedCode),
    ]
