# Generated by Django 3.2.11 on 2022-11-10 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0031_alter_evaluationinitiationpage_dashboard_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='objectivity',
            field=models.CharField(choices=[('objective', 'Objective'), ('subjective', 'Subjective')], default='subjective', help_text="Ce champ n'est pas modifiable après la création de la question", max_length=32, verbose_name='Objective / Subjective (Non modifiable)'),
        ),
    ]
