# Generated by Django 3.2.11 on 2022-04-29 09:19

import datetime
from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields
import wagtail.search.index


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('open_democracy_back', '0032_auto_20220426_0808'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=64, verbose_name='Prénom et nom')),
                ('person_context', models.CharField(help_text='Exemple : Elu de Strasbourg, Membre de Démocratie Ouverte, Habitant de Toulouse ... ', max_length=64, verbose_name='Context de la personne')),
                ('quote', models.CharField(default='', max_length=255, verbose_name='Citation')),
                ('publish', models.BooleanField(default=False, verbose_name="Publier dans la page d'accueil")),
            ],
            options={
                'verbose_name': "Retour d'expériences",
                'verbose_name_plural': "Retours d'expériences",
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
        migrations.AddField(
            model_name='homepage',
            name='blog_block_intro',
            field=models.CharField(blank=True, max_length=255, verbose_name='Intro du bloc Blog'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='blog_block_title',
            field=models.CharField(blank=True, help_text="Si ce champ est vide les articles de blog ne s'afficheront pas sur l'accueil", max_length=68, verbose_name='Titre du bloc Blog'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='feedback_block_intro',
            field=models.CharField(blank=True, max_length=255, verbose_name="Intro du bloc retours d'expérience"),
        ),
        migrations.AddField(
            model_name='homepage',
            name='feedback_block_title',
            field=models.CharField(blank=True, help_text="Si ce champ est vide les retours d'expérience ne s'afficheront pas sur l'accueil", max_length=68, verbose_name="Titre du bloc retours d'expérience"),
        ),
        migrations.AddField(
            model_name='homepage',
            name='partner_block_intro',
            field=models.CharField(blank=True, max_length=255, verbose_name='Intro du bloc Partenaires'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='partner_block_title',
            field=models.CharField(blank=True, help_text="Si ce champ est vide le bloc Partenaires ne s'afficheront pas sur l'accueil", max_length=68, verbose_name='Titre du bloc Partenaires'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='resources_block_intro',
            field=models.CharField(blank=True, max_length=255, verbose_name='Intro du bloc Ressources'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='resources_block_title',
            field=models.CharField(blank=True, help_text="Si ce champ est vide bloc Ressources ne s'afficheront pas sur l'accueil", max_length=68, verbose_name='Titre du bloc Ressources'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='tag_line',
            field=models.CharField(default='', max_length=255, verbose_name="Phrase d'accroche"),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='introduction',
            field=wagtail.core.fields.RichTextField(default='', verbose_name='Introduction'),
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Title')),
                ('publication_date', models.DateTimeField(default=datetime.datetime.now, help_text="Permet de trier l'ordre d'affichage des articles de blog", verbose_name='Date de publication')),
                ('short_description', models.CharField(blank=True, max_length=510, null=True, verbose_name='Description courte')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Logo du partenaire')),
            ],
            options={
                'verbose_name': 'Ressource',
                'verbose_name_plural': 'Ressources',
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Nom')),
                ('lago_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image', verbose_name='Logo du partenaire')),
            ],
            options={
                'verbose_name': 'Partenaire',
                'verbose_name_plural': 'Partenaires',
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Title')),
                ('publication_date', models.DateTimeField(default=datetime.datetime.now, help_text="Permet de trier l'ordre d'affichage des articles de blog", verbose_name='Date de publication')),
                ('short_description', models.CharField(blank=True, max_length=510, null=True, verbose_name='Description courte')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Logo du partenaire')),
            ],
            options={
                'verbose_name': 'Article de blog',
                'verbose_name_plural': 'Articles de blog',
                'ordering': ['-publication_date'],
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
    ]
