# Generated by Django 3.2.11 on 2022-04-21 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0032_alter_evaluationinitpage_representativity_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationinitpage',
            name='public_name_question_description',
            field=models.TextField(default='', help_text="Expliciter à l'utilisateur ce qu'implique ou non d'autoriser à publier son nom", verbose_name="Description de la question sur la publication ou non du nom de l'initateur"),
        ),
    ]
