# Generated by Django 3.2.11 on 2022-05-06 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0033_auto_20220429_0919_squashed_0037_auto_20220429_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='mandatory',
            field=models.BooleanField(default=False, verbose_name='Obligatoire'),
        ),
        migrations.AddField(
            model_name='response',
            name='has_passed',
            field=models.BooleanField(default=False),
        ),
    ]
