# Generated by Django 3.2.11 on 2022-11-17 14:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0007_add_autocreate_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailcore', '0066_collection_management_permissions'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('open_democracy_back', '0033_evaluationboardpage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EvaluationBoardPage',
            new_name='ParticipationBoardPage',
        ),
    ]
