# Generated by Django 3.2.11 on 2022-04-22 10:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0033_evaluationinitpage_public_name_question_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assessment',
            old_name='initiated_by',
            new_name='initiated_by_user',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='carried_by',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='is_carried_by_locality',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='is_initiated_by_locality',
        ),
        migrations.AddField(
            model_name='assessment',
            name='initialized_to_the_name_of',
            field=models.CharField(blank=True, help_text="Utile quand l'évaluation n'est pas initialisé par la collectivité", max_length=255, null=True, verbose_name='Initialisé au nom de'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='initiator_type',
            field=models.CharField(blank=True, choices=[('collectivity', 'La collectivité'), ('association', 'Une association')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='public_initiator',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='representativitycriteria',
            name='min_rate',
            field=models.IntegerField(default=0, help_text='En dessous de ce taux (%) la publication des résultats est interdite', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Taux (en %) minimum acceptable pour la publication des résultats'),
        ),
    ]
