# Generated by Django 3.2.11 on 2022-05-11 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0034_auto_20220509_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='mandatory',
            field=models.BooleanField(default=False, verbose_name='Obligatoire'),
        ),
        migrations.AddField(
            model_name='response',
            name='has_passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='percentagerange',
            name='associated_score',
            field=models.IntegerField(help_text='Si pertinant.', verbose_name='Score associé'),
        ),
        migrations.AlterField(
            model_name='question',
            name='false_associated_score',
            field=models.IntegerField(blank=True, help_text='Si pertinant', null=True, verbose_name='Score associé à une réponse négative'),
        ),
        migrations.AlterField(
            model_name='question',
            name='true_associated_score',
            field=models.IntegerField(blank=True, help_text='Si pertinant', null=True, verbose_name='Score associé à une réponse positive'),
        ),
        migrations.AlterField(
            model_name='responsechoice',
            name='associated_score',
            field=models.IntegerField(blank=True, help_text='Si pertinant', null=True, verbose_name='Score associé'),
        ),
    ]
