# Generated by Django 3.2.11 on 2022-04-22 15:11

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0034_auto_20220422_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluationinitpage',
            name='representativity_question',
        ),
        migrations.AddField(
            model_name='evaluationinitpage',
            name='initialization_validation',
            field=wagtail.core.fields.RichTextField(default='', help_text="S'affichera une fois l'initialisation de l'évaluation terminée", verbose_name="Texte de validation de l'initialisation d'une évaluation"),
        ),
        migrations.AddField(
            model_name='evaluationinitpage',
            name='representativity_title',
            field=models.TextField(default='', help_text="Correspond à la partie où seront posées les questions sur les seuils d'acceptabilité de la représentativité", verbose_name="Titre pour les questions sur les seuils d'acceptabilité de la représentativité"),
        ),
        migrations.AlterField(
            model_name='evaluationinitpage',
            name='representativity_description',
            field=wagtail.core.fields.RichTextField(default='', help_text='Permet à la personne de mieux comprendre les questions sur les représentativités, et lui donne des éléments de réponse', verbose_name='Description de la question sur la limite de représentativité'),
        ),
    ]
