# Generated by Django 3.2.12 on 2023-06-27 09:32

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0034_rename_evaluationboardpage_participationboardpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmenttype',
            name='name',
        ),
        migrations.AlterField(
            model_name='assessmenttype',
            name='assessment_type',
            field=models.CharField(choices=[('quick', 'Diagnostic rapide'), ('participative', 'Evaluation participative'), ('with_expert', 'Evaluation avec expert')], editable=False, max_length=32, unique=True, verbose_name='Evaluation géré par le code'),
        ),
        migrations.AlterField(
            model_name='usagepage',
            name='start_assessment_block_data',
            field=wagtail.fields.StreamField([('assessment_type', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(label='Titre')), ('type', wagtail.blocks.ChoiceBlock(choices=[('quick', 'Diagnostic rapide'), ('participative', 'Evaluation participative'), ('with_expert', 'Evaluation avec expert')], label='Type')), ('pdf_button', wagtail.blocks.CharBlock(label='Label du bouton pour le pdf'))], label="Type d'évaluation", label_format='Evaluation : {title}'))], blank=True, help_text="Pour modifier le descriptif de chaque type d'évaluation il faut directement aller dans le type d'évaluation correspondant", verbose_name="Descriptif des différents types d'évaluation"),
        ),
    ]
