# Generated by Django 3.2.11 on 2022-05-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0035_auto_20220511_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('open', 'Ouverte'), ('unique_choice', 'Choix unique'), ('multiple_choice', 'Choix multiple'), ('closed_with_scale', 'Fermée à échelle'), ('boolean', 'Binaire oui / non'), ('percentage', 'Pourcentage')], default='boolean', help_text='Choisir le type de question', max_length=32),
        ),
    ]
