# Generated by Django 3.2.12 on 2023-06-27 09:35

from django.db import migrations
from open_democracy_back.utils import ManagedAssessmentType



def add_assessment_types(apps, schema_editor):
    AssessmentType = apps.get_model('open_democracy_back', 'AssessmentType')
    if not AssessmentType.objects.all().exists():
        for assessment_type in ManagedAssessmentType:
            AssessmentType.objects.create(assessment_type=assessment_type)

class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0035_auto_20230627_0932'),
    ]

    operations = [
        migrations.RunPython(add_assessment_types, migrations.RunPython.noop),
    ]
