# Generated by Django 3.2.11 on 2022-05-30 07:50

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields

from open_democracy_back.models.questionnaire_and_profiling_models import Criteria


def moveDescriptionsFromQuestionToCriteria(apps, _):
    Question = apps.get_model("open_democracy_back", "Question")
    questionnaire_questions = Question.objects.all()
    for questionnaire_question in questionnaire_questions:
        if questionnaire_question.criteria:
            criteria = questionnaire_question.criteria
            criteria.legal_frame = questionnaire_question.legal_frame
            criteria.sources = questionnaire_question.sources
            criteria.to_go_further = questionnaire_question.to_go_further
            criteria.use_case = questionnaire_question.use_case
            criteria.save()


def moveDescriptionsFromCriteriaToQuestion(apps, _):
    Criteria = apps.get_model("open_democracy_back", "Criteria")
    criterias = Criteria.objects.all()
    for criteria in criterias:
        questionnaire_questions = criteria.questions.all()
        for questionnaire_question in questionnaire_questions:
            questionnaire_question.legal_frame = criteria.legal_frame
            questionnaire_question.sources = criteria.sources
            questionnaire_question.to_go_further = criteria.to_go_further
            questionnaire_question.use_case = criteria.use_case
            questionnaire_question.save()


class Migration(migrations.Migration):

    dependencies = [
        ("open_democracy_back", "0036_alter_question_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="CriteriaDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="criteriadefinition",
            name="criteria",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="related_definition_ordered",
                to="open_democracy_back.criteria",
            ),
        ),
        migrations.AddField(
            model_name="criteriadefinition",
            name="definition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="open_democracy_back.definition",
            ),
        ),
        migrations.AddField(
            model_name="criteria",
            name="legal_frame",
            field=wagtail.core.fields.RichTextField(
                blank=True, null=True, verbose_name="Cadre légal"
            ),
        ),
        migrations.AddField(
            model_name="criteria",
            name="sources",
            field=wagtail.core.fields.RichTextField(
                blank=True, null=True, verbose_name="Sources"
            ),
        ),
        migrations.AddField(
            model_name="criteria",
            name="to_go_further",
            field=wagtail.core.fields.RichTextField(
                blank=True, null=True, verbose_name="Pour aller plus loin"
            ),
        ),
        migrations.AddField(
            model_name="criteria",
            name="use_case",
            field=wagtail.core.fields.RichTextField(
                blank=True, null=True, verbose_name="Exemples inspirants"
            ),
        ),
        migrations.RunPython(
            moveDescriptionsFromQuestionToCriteria,
            moveDescriptionsFromCriteriaToQuestion,
        ),
        migrations.RemoveField(
            model_name="question",
            name="legal_frame",
        ),
        migrations.RemoveField(
            model_name="question",
            name="sources",
        ),
        migrations.RemoveField(
            model_name="question",
            name="to_go_further",
        ),
        migrations.RemoveField(
            model_name="question",
            name="use_case",
        ),
        migrations.DeleteModel(
            name="QuestionDefinition",
        ),
    ]
