# Generated by Django 3.2.12 on 2023-06-27 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0035_auto_20230621_1323'),
        ('open_democracy_back', '0036_auto_20230627_0935'),
    ]

    operations = [
    ]
