# Generated by Django 3.2.11 on 2022-05-30 09:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


def deleteParticipations(apps, _):
    Participation = apps.get_model("open_democracy_back", "Participation")
    Participation.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("open_democracy_back", "0037_auto_20220530_0750"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParticipationResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("has_passed", models.BooleanField(default=False)),
                ("boolean_response", models.BooleanField(blank=True, null=True)),
                (
                    "percentage_response",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "multiple_choice_response",
                    models.ManyToManyField(
                        related_name="multiple_choice_participationresponses",
                        to="open_democracy_back.ResponseChoice",
                    ),
                ),
                (
                    "participation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="open_democracy_back.participation",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participationresponses",
                        to="open_democracy_back.question",
                    ),
                ),
                (
                    "unique_choice_response",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="unique_choice_participationresponses",
                        to="open_democracy_back.responsechoice",
                    ),
                ),
            ],
            options={
                "unique_together": {("participation", "question")},
            },
        ),
        migrations.CreateModel(
            name="AssessmentResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("has_passed", models.BooleanField(default=False)),
                ("boolean_response", models.BooleanField(blank=True, null=True)),
                (
                    "percentage_response",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="open_democracy_back.assessment",
                    ),
                ),
                (
                    "multiple_choice_response",
                    models.ManyToManyField(
                        related_name="multiple_choice_assessmentresponses",
                        to="open_democracy_back.ResponseChoice",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessmentresponses",
                        to="open_democracy_back.question",
                    ),
                ),
                (
                    "unique_choice_response",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="unique_choice_assessmentresponses",
                        to="open_democracy_back.responsechoice",
                    ),
                ),
            ],
            options={
                "unique_together": {("assessment", "question")},
            },
        ),
        migrations.AlterField(
            model_name="closedwithrankingresponse",
            name="response",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="closed_with_ranking_responses_ordered",
                to="open_democracy_back.participationresponse",
            ),
        ),
        migrations.AlterField(
            model_name="closedwithscalecategoryresponse",
            name="response",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="closed_with_scale_response_categories",
                to="open_democracy_back.participationresponse",
            ),
        ),
        migrations.RunPython(deleteParticipations),
        migrations.DeleteModel(
            name="Response",
        ),
    ]
