# Generated by Django 3.2.12 on 2023-06-28 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0037_auto_20230628_0853'),
        ('open_democracy_back', '0038_alter_participant_email'),
    ]

    operations = [
    ]
