# Generated by Django 3.2.11 on 2022-05-31 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('open_democracy_back', '0038_auto_20220530_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentresponse',
            name='answered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_responses', to=settings.AUTH_USER_MODEL),
        ),
    ]
