# Generated by Django 3.2.12 on 2023-07-04 15:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0039_merge_20230628_1353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='numberrange',
            options={'ordering': ['sort_order'], 'verbose_name': 'Score pour une fourchette donnée', 'verbose_name_plural': 'Scores pour les différentes fourchettes'},
        ),
        migrations.AlterModelOptions(
            name='percentagerange',
            options={'ordering': ['sort_order'], 'verbose_name': 'Score pour une fourchette donnée', 'verbose_name_plural': 'Scores pour les différentes fourchettes'},
        ),
        migrations.AlterField(
            model_name='numberrange',
            name='associated_score',
            field=models.IntegerField(blank=True, help_text='Si pertinent', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='Score associé'),
        ),
    ]
