# Generated by Django 3.2.11 on 2022-06-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0039_auto_20220601_1345'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'verbose_name': 'Article de blog', 'verbose_name_plural': 'Articles de blog'},
        ),
        migrations.AddField(
            model_name='blogpost',
            name='pillars',
            field=models.ManyToManyField(blank=True, related_name='blogposts', to='open_democracy_back.Pillar', verbose_name='Piliers concernés'),
        ),
        migrations.AddField(
            model_name='resource',
            name='pillars',
            field=models.ManyToManyField(blank=True, related_name='resources', to='open_democracy_back.Pillar', verbose_name='Piliers concernés'),
        ),
    ]
