# Generated by Django 3.2.11 on 2022-05-31 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0039_assessmentresponse_answered_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='is_initialization_questions_completed',
            field=models.BooleanField(default=False),
        ),
    ]
