# Generated by Django 3.2.11 on 2022-06-06 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('open_democracy_back', '0040_auto_20220602_1552'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-publication_date'], 'verbose_name': 'Article de blog', 'verbose_name_plural': 'Articles de blog'},
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['-publication_date'], 'verbose_name': 'Ressource', 'verbose_name_plural': 'Ressources'},
        ),
        migrations.AddField(
            model_name='homepage',
            name='intro_youtube_video_id',
            field=models.CharField(blank=True, help_text="Indiquer ici seulement l'id de la video youtube, celui-ci est indiqué dans l'url après 'v='. Exemple : pour https://www.youtube.com/watch?v=xMQMvVIB0vM renseigner xMQMvVIB0vM", max_length=15, null=True, verbose_name='Vidéo Youtube (id)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='intro_image',
            field=models.ForeignKey(blank=True, help_text="Si l'id d'une vidéo youtube est indiqué alors l'image ne sera pas affiché sur la page d'accueil", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image'),
        ),
    ]
