# Generated by Django 3.2.19 on 2023-07-10 09:42

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0040_auto_20230704_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='content',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(form_classname='full title', label='Titre de la page')), ('section', wagtail.core.blocks.StructBlock([('paragraph', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'h3', 'h4', 'ol', 'ul', 'document-link', 'h2'], label='Contenu', required=True)), ('color', wagtail.core.blocks.ChoiceBlock(choices=[('blue-light', 'Bleue'), ('secondary-light', 'Rose'), ('white', 'Blanche'), ('', 'Sans couleur')], help_text='Couleur de fond', label='couleur', required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(label='Image à côté du paragraphe', required=False)), ('position', wagtail.core.blocks.ChoiceBlock(choices=[('right', 'Droite'), ('left', 'Gauche')], help_text="Position de l'image", required=False)), ('sub_section', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('color', wagtail.core.blocks.ChoiceBlock(choices=[('blue-light', 'Bleue'), ('secondary-light', 'Rose'), ('white', 'Blanche'), ('', 'Sans couleur')], help_text='Couleur de fond', label='couleur', required=False)), ('paragraph', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'h3', 'h4', 'ol', 'ul', 'document-link'], label='Contenu', required=False)), ('columns', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('color', wagtail.core.blocks.ChoiceBlock(choices=[('blue-light', 'Bleue'), ('secondary-light', 'Rose'), ('white', 'Blanche'), ('', 'Sans couleur')], help_text='Couleur de fond', label='couleur', required=False)), ('paragraph', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'h3', 'h4', 'ol', 'ul', 'document-link'], label='Contenu', required=False))], label='Colonne'), label='Colonnes'))], label='Sous section'), default=[], label='Sous sections'))], label='Section')), ('image', wagtail.images.blocks.ImageChooserBlock()), ('pdf', wagtail.documents.blocks.DocumentChooserBlock())], blank=True, help_text="Corps de l'article", verbose_name='Contenu'),
        ),
        migrations.AddField(
            model_name='resource',
            name='content',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(form_classname='full title', label='Titre de la page')), ('section', wagtail.core.blocks.StructBlock([('paragraph', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'h3', 'h4', 'ol', 'ul', 'document-link', 'h2'], label='Contenu', required=True)), ('color', wagtail.core.blocks.ChoiceBlock(choices=[('blue-light', 'Bleue'), ('secondary-light', 'Rose'), ('white', 'Blanche'), ('', 'Sans couleur')], help_text='Couleur de fond', label='couleur', required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(label='Image à côté du paragraphe', required=False)), ('position', wagtail.core.blocks.ChoiceBlock(choices=[('right', 'Droite'), ('left', 'Gauche')], help_text="Position de l'image", required=False)), ('sub_section', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('color', wagtail.core.blocks.ChoiceBlock(choices=[('blue-light', 'Bleue'), ('secondary-light', 'Rose'), ('white', 'Blanche'), ('', 'Sans couleur')], help_text='Couleur de fond', label='couleur', required=False)), ('paragraph', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'h3', 'h4', 'ol', 'ul', 'document-link'], label='Contenu', required=False)), ('columns', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('color', wagtail.core.blocks.ChoiceBlock(choices=[('blue-light', 'Bleue'), ('secondary-light', 'Rose'), ('white', 'Blanche'), ('', 'Sans couleur')], help_text='Couleur de fond', label='couleur', required=False)), ('paragraph', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'h3', 'h4', 'ol', 'ul', 'document-link'], label='Contenu', required=False))], label='Colonne'), label='Colonnes'))], label='Sous section'), default=[], label='Sous sections'))], label='Section')), ('image', wagtail.images.blocks.ImageChooserBlock()), ('pdf', wagtail.documents.blocks.DocumentChooserBlock())], blank=True, help_text="Corps de l'article", verbose_name='Contenu'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='initiator_type',
            field=models.CharField(blank=True, choices=[('collectivity', 'La collectivité'), ('association', 'Une association'), ('individual', 'Un particulier'), ('other', 'Autre')], max_length=32, null=True, verbose_name="type d'initilisateur"),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='external_link',
            field=models.CharField(blank=True, help_text="Si ce champ est rempli, le corps de l'article sera ignoré", max_length=300, null=True, verbose_name='Lien externe'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='external_link',
            field=models.CharField(blank=True, help_text="Si ce champ est rempli, le corps de l'article sera ignoré", max_length=300, null=True, verbose_name='Lien externe'),
        ),
    ]
