# Generated by Django 3.2.19 on 2023-07-11 09:48

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks
import wagtail.images.blocks
from django.utils.text import slugify


def add_slugs(apps, _):
    BlogPost = apps.get_model("open_democracy_back", "BlogPost")
    Resource = apps.get_model("open_democracy_back", "Resource")
    for model in [BlogPost, Resource]:
        for instance in model.objects.all():
            instance.slug = slugify(instance.title)
            instance.save()


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0041_auto_20230710_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='slug',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='slug',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(form_classname='full title', label='Titre de la page')), ('section', wagtail.core.blocks.StructBlock([('paragraph', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'h3', 'h4', 'ol', 'ul', 'document-link', 'h2'], label='Contenu', required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(label='Image à côté du paragraphe', required=False)), ('position', wagtail.core.blocks.ChoiceBlock(choices=[('right', 'Droite'), ('left', 'Gauche')], help_text="Position de l'image", required=False)), ('sub_section', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('paragraph', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'h3', 'h4', 'ol', 'ul', 'document-link'], label='Contenu', required=False)), ('columns', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('paragraph', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'h3', 'h4', 'ol', 'ul', 'document-link'], label='Contenu', required=False))], label='Colonne'), label='Colonnes'))], label='Sous section'), default=[], label='Sous sections'))], label='Section')), ('image', wagtail.images.blocks.ImageChooserBlock()), ('pdf', wagtail.documents.blocks.DocumentChooserBlock())], blank=True, help_text="Corps de l'article", verbose_name='Contenu'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='short_description',
            field=models.CharField(blank=True, help_text='Ce texte apparait sur la miniature', max_length=1024, null=True, verbose_name='Description courte'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='content',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(form_classname='full title', label='Titre de la page')), ('section', wagtail.core.blocks.StructBlock([('paragraph', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'h3', 'h4', 'ol', 'ul', 'document-link', 'h2'], label='Contenu', required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(label='Image à côté du paragraphe', required=False)), ('position', wagtail.core.blocks.ChoiceBlock(choices=[('right', 'Droite'), ('left', 'Gauche')], help_text="Position de l'image", required=False)), ('sub_section', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('paragraph', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'h3', 'h4', 'ol', 'ul', 'document-link'], label='Contenu', required=False)), ('columns', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('paragraph', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'h3', 'h4', 'ol', 'ul', 'document-link'], label='Contenu', required=False))], label='Colonne'), label='Colonnes'))], label='Sous section'), default=[], label='Sous sections'))], label='Section')), ('image', wagtail.images.blocks.ImageChooserBlock()), ('pdf', wagtail.documents.blocks.DocumentChooserBlock())], blank=True, help_text="Corps de l'article", verbose_name='Contenu'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='short_description',
            field=models.CharField(blank=True, help_text='Ce texte apparait sur la miniature', max_length=1024, null=True, verbose_name='Description courte'),
        ),
        migrations.RunPython(add_slugs, migrations.RunPython.noop),
    ]
