# Generated by Django 3.2.11 on 2022-06-09 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0041_auto_20220606_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='short_description',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Description courte'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='short_description',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Description courte'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Title'),
        ),
    ]
