# Generated by Django 3.2.19 on 2023-07-11 16:16

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0042_auto_20230711_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(form_classname='full title', label='Titre de la page')), ('section', wagtail.core.blocks.StructBlock([('paragraph', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'h3', 'h4', 'ol', 'ul', 'document-link', 'h2'], label='Contenu', required=True))], label='Section')), ('image', wagtail.images.blocks.ImageChooserBlock()), ('pdf', wagtail.documents.blocks.DocumentChooserBlock())], blank=True, help_text="Corps de l'article", verbose_name='Contenu'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='content',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(form_classname='full title', label='Titre de la page')), ('section', wagtail.core.blocks.StructBlock([('paragraph', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'h3', 'h4', 'ol', 'ul', 'document-link', 'h2'], label='Contenu', required=True))], label='Section')), ('image', wagtail.images.blocks.ImageChooserBlock()), ('pdf', wagtail.documents.blocks.DocumentChooserBlock())], blank=True, help_text="Corps de l'article", verbose_name='Contenu'),
        ),
    ]
