# Generated by Django 3.2.19 on 2023-07-13 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0042_auto_20230713_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='external_link',
            field=models.URLField(blank=True, help_text="Si ce champ est rempli, le corps de l'article sera ignoré", max_length=300, null=True, verbose_name='Lien externe'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='external_link',
            field=models.URLField(blank=True, help_text="Si ce champ est rempli, le corps de l'article sera ignoré", max_length=300, null=True, verbose_name='Lien externe'),
        ),
    ]
