# Generated by Django 3.2.11 on 2022-06-09 16:07

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0012_uploadeddocument'),
        ('open_democracy_back', '0043_auto_20220607_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmenttype',
            name='for_what',
            field=models.CharField(blank=True, max_length=510, verbose_name='Ce que ça permet'),
        ),
        migrations.AddField(
            model_name='assessmenttype',
            name='for_who',
            field=models.CharField(blank=True, max_length=510, verbose_name="A qui c'est adressé"),
        ),
        migrations.AddField(
            model_name='assessmenttype',
            name='pdf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='Pdf du questionnaire'),
        ),
        migrations.AddField(
            model_name='assessmenttype',
            name='price',
            field=models.CharField(blank=True, max_length=510, verbose_name='Le prix'),
        ),
        migrations.AddField(
            model_name='assessmenttype',
            name='results',
            field=models.CharField(blank=True, max_length=510, verbose_name='Les résultats'),
        ),
        migrations.AddField(
            model_name='assessmenttype',
            name='what',
            field=models.CharField(blank=True, max_length=510, verbose_name='Ce que ça contient'),
        ),
        migrations.AlterField(
            model_name='assessmenttype',
            name='assessment_type',
            field=models.CharField(choices=[('quick', 'Diagnostic rapide'), ('participative', 'Evaluation participative'), ('with_expert', 'Evaluation avec experts')], max_length=32, unique=True, verbose_name='Evaluation géré par le code'),
        ),
        migrations.AlterField(
            model_name='assessmenttype',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='usagepage',
            name='participate_left_paragraph',
            field=wagtail.core.fields.RichTextField(blank=True, default='', verbose_name='Paragraphe de gauche'),
        ),
        migrations.AlterField(
            model_name='usagepage',
            name='participate_right_paragraph',
            field=wagtail.core.fields.RichTextField(blank=True, default='', verbose_name='Paragraphe de droite'),
        ),
        migrations.AlterField(
            model_name='usagepage',
            name='start_processes',
            field=wagtail.core.fields.StreamField([('assessment_type', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(label='Titre')), ('type', wagtail.core.blocks.ChoiceBlock(choices=[('quick', 'Diagnostic rapide'), ('participative', 'Evaluation participative'), ('with_expert', 'Evaluation avec experts')], label='Type')), ('pdf_button', wagtail.core.blocks.CharBlock(label='Label du bouton pour le pdf'))], label="Type d'évaluation", label_format='Evaluation : {title}'))], blank=True, help_text="Pour modifier le descriptif de chaque type d'évaluation il faut directement aller dans le type d'évaluation correspondant", verbose_name="Descriptif des différents types d'évaluation"),
        ),
        migrations.AlterField(
            model_name='usagepage',
            name='steps_of_use',
            field=wagtail.core.fields.StreamField([('step', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(label='Image')), ('title', wagtail.core.blocks.CharBlock(label='Titre')), ('description', wagtail.core.blocks.TextBlock(label='Description'))], label='Etape', label_format='Etape : {title}'))], blank=True, verbose_name="Etapes d'utilisation"),
        ),
        migrations.RenameField(
            model_name='usagepage',
            old_name='start_processes',
            new_name='start_assessment_block_data',
        ),
    ]
