# Generated by Django 3.2.19 on 2023-08-30 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0043_auto_20230713_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
