# Generated by Django 3.2.11 on 2022-06-15 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('open_democracy_back', '0044_auto_20220609_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationQuestionnairePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('start_title', models.CharField(max_length=128, verbose_name='Titre')),
                ('start_text', models.TextField(default='', verbose_name='Texte')),
                ('intermediate_step_title', models.CharField(max_length=128, verbose_name='Titre')),
                ('is_intermediate_step_title_with_pillar_names', models.BooleanField(default=True, verbose_name='Afficher dans le titre le liste des piliers terminés')),
                ('intermediate_step_text_logged_in', models.TextField(default='', verbose_name='Texte pour un utilisateur connecté')),
                ('intermediate_step_text_logged_out', models.TextField(default='', verbose_name='Texte pour un utilisateur non connecté')),
                ('finished_title', models.CharField(max_length=128, verbose_name='Titre')),
                ('finished_text_logged_in', models.TextField(default='', verbose_name='Texte pour un utilisateur connecté')),
                ('finished_text_logged_out', models.TextField(default='', verbose_name='Texte pour un utilisateur non connecté')),
            ],
            options={
                'verbose_name': "Déroulement de l'évaluation",
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='usagepage',
            name='participate_block_intro',
            field=models.CharField(blank=True, max_length=510, verbose_name='Intro'),
        ),
        migrations.AlterField(
            model_name='usagepage',
            name='participate_block_title',
            field=models.CharField(blank=True, help_text="Si ce champ est vide les étapes d'utilisation du DémoMètre ne s'afficheront pas", max_length=68, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='usagepage',
            name='start_assessment_block_intro',
            field=models.CharField(blank=True, max_length=510, verbose_name='Intro'),
        ),
        migrations.AlterField(
            model_name='usagepage',
            name='start_assessment_block_title',
            field=models.CharField(blank=True, help_text="Si ce champ est vide les étapes d'utilisation du DémoMètre ne s'afficheront pas", max_length=68, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='usagepage',
            name='step_of_use_intro',
            field=models.CharField(blank=True, max_length=510, verbose_name='Intro'),
        ),
        migrations.AlterField(
            model_name='usagepage',
            name='step_of_use_title',
            field=models.CharField(blank=True, help_text="Si ce champ est vide les étapes d'utilisation du DémoMètre ne s'afficheront pas", max_length=68, verbose_name='Titre'),
        ),
    ]
