# Generated by Django 3.2.11 on 2022-06-10 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0044_auto_20220609_1607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usagepage',
            old_name='start_processes',
            new_name='start_assessment_block_data',
        ),
    ]
