# Generated by Django 3.2.13 on 2022-06-07 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0044_auto_20220609_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='referentialpage',
            name='pillar_block_title',
            field=models.CharField(blank=True, help_text="si ce champs est vide l'explication des piliers ne s'affichera pas", max_length=68, verbose_name='Titre explication pilier'),
        ),
    ]
