# Generated by Django 3.2.13 on 2022-06-16 16:25

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('open_democracy_back', '0045_auto_20220615_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='referentialpage',
            name='criteria_block_content',
            field=wagtail.core.fields.RichTextField(default='', verbose_name='Contenu'),
        ),
        migrations.AddField(
            model_name='referentialpage',
            name='criteria_block_title',
            field=models.CharField(blank=True, help_text="si ce champs est vide l'explication des critères d'évaluation ne s'affichera pas", max_length=68, verbose_name='Titre'),
        ),
        migrations.AddField(
            model_name='referentialpage',
            name='description',
            field=wagtail.core.fields.RichTextField(default='', verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='referentialpage',
            name='marker_block_content',
            field=wagtail.core.fields.RichTextField(default='', verbose_name='Contenu'),
        ),
        migrations.AddField(
            model_name='referentialpage',
            name='marker_block_title',
            field=models.CharField(blank=True, help_text="si ce champs est vide l'explication des marqueurs ne s'affichera pas", max_length=68, verbose_name='Titre'),
        ),
        migrations.AddField(
            model_name='referentialpage',
            name='pillar_block_content',
            field=wagtail.core.fields.RichTextField(default='', verbose_name='Contenu'),
        ),
        migrations.AddField(
            model_name='referentialpage',
            name='pillar_block_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='referentialpage',
            name='pillar_block_title',
            field=models.CharField(blank=True, help_text="si ce champs est vide l'explication des piliers ne s'affichera pas", max_length=68, verbose_name='Titre'),
        ),
    ]
