# Generated by Django 3.2.11 on 2022-06-17 09:15

from django.db import migrations, models
import django.db.models.deletion
import open_democracy_back.models.contents_models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('wagtailimages', '0023_add_choose_permissions'),
        ('open_democracy_back', '0045_auto_20220615_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('tag_line', models.CharField(default='', max_length=510, verbose_name="Phrase d'accroche")),
                ('introduction', wagtail.core.fields.RichTextField(blank=True, default='', verbose_name='Introduction')),
                ('why_block_title', models.CharField(blank=True, help_text="Si ce champ est vide le bloc ne s'affichera pas", max_length=68, verbose_name='Titre')),
                ('why_block_text', wagtail.core.fields.RichTextField(blank=True, default='', verbose_name='Texte')),
                ('objective_block_title', models.CharField(blank=True, help_text="Si ce champ est vide le bloc ne s'affichera pas", max_length=68, verbose_name='Titre')),
                ('objective_block_data', wagtail.core.fields.StreamField([('objective', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(help_text='Utiliser de préférence un format svg', label='Image')), ('title', wagtail.core.blocks.CharBlock(label='Titre'))], label='Objectif', label_format='Objectif : {title}'))], blank=True, verbose_name='Les objectifs')),
                ('impact_block_title', models.CharField(blank=True, help_text="Si ce champ est vide le bloc ne s'affichera pas", max_length=68, verbose_name='Titre')),
                ('impact_block_data', wagtail.core.fields.StreamField([('impact', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(label='Image')), ('title', wagtail.core.blocks.CharBlock(label='Titre'))], label='Impact', label_format='Impact : {title}'))], blank=True, verbose_name='Les impacts')),
                ('who_block_title', models.CharField(blank=True, help_text="Si ce champ est vide le bloc ne s'affichera pas", max_length=68, verbose_name='Titre')),
                ('who_partner_sub_block_title', models.CharField(blank=True, help_text="Si ce champ est vide le bloc ne s'affichera pas", max_length=68, verbose_name='Titre - partenaires')),
                ('who_partner_sub_block_data', wagtail.core.fields.StreamField([('group', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(label='Titre')), ('description', wagtail.core.blocks.CharBlock(label='Description')), ('partners', wagtail.core.blocks.ListBlock(wagtail.snippets.blocks.SnippetChooserBlock(open_democracy_back.models.contents_models.Partner)))], label='Type de partenaires', label_format='{title}'))])),
                ('how_block_title', models.CharField(blank=True, help_text="Si ce champ est vide le bloc ne s'affichera pas", max_length=68, verbose_name='Titre')),
                ('how_block_data', wagtail.core.fields.StreamField([('title', wagtail.core.blocks.CharBlock(label='Titre')), ('paragraph', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'ol', 'ul'], label='Paragraphe')), ('cards', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(help_text='Utiliser de préférence un format svg', label='Image')), ('title', wagtail.core.blocks.CharBlock(label='Titre')), ('details', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'ol', 'ul'], label='Descriptif')), ('link', wagtail.core.blocks.CharBlock(label='Lien en savoir plus'))]), label='Carte', label_format='Carte : {title}'))], blank=True, verbose_name='Les impacts')),
                ('intro_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Page du projet',
            },
            bases=('wagtailcore.page',),
        ),
    ]
