# Generated by Django 3.2.13 on 2022-06-13 14:08

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('open_democracy_back', '0045_referentialpage_pillar_block_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='referentialpage',
            name='criteria_block_content',
            field=wagtail.core.fields.RichTextField(default='', help_text="s'il n'y a pas de contenu l'explication des critères d'évaluation ne s'affichera pas", verbose_name='Contenu textuelle critères évaluation'),
        ),
        migrations.AddField(
            model_name='referentialpage',
            name='criteria_block_title',
            field=models.CharField(blank=True, help_text="si ce champs est vide l'explication des critères d'évaluation ne s'affichera pas", max_length=68, verbose_name='Titre explication critères évaluation'),
        ),
        migrations.AddField(
            model_name='referentialpage',
            name='marker_block_content',
            field=wagtail.core.fields.RichTextField(default='', help_text="s'il n'y a pas de contenu l'explication des marqueurs ne s'affichera pas", verbose_name='Contenu textuelle marqueurs'),
        ),
        migrations.AddField(
            model_name='referentialpage',
            name='marker_block_title',
            field=models.CharField(blank=True, help_text="si ce champs est vide l'explication des marqueurs ne s'affichera pas", max_length=68, verbose_name='Titre explication marqueurs'),
        ),
        migrations.AddField(
            model_name='referentialpage',
            name='pillar_block_content',
            field=wagtail.core.fields.RichTextField(default='', help_text="s'il n'y a pas de contenu l'explication des piliers ne s'affichera pas", verbose_name='Contenu textuelle piliers'),
        ),
        migrations.AddField(
            model_name='referentialpage',
            name='pillar_block_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image'),
        ),
    ]
