# Generated by Django 3.2.19 on 2023-09-11 14:19

from django.db import migrations, models
import open_democracy_back.models.utils


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0045_auto_20230905_0652'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='medium',
            field=models.CharField(choices=[('online', 'en ligne'), ('paper', 'papier')], default='online', max_length=6, verbose_name='Support de réponse'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='comments',
            field=open_democracy_back.models.utils.FrontendRichText(blank=True, default='', verbose_name='commentaires'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='context',
            field=open_democracy_back.models.utils.FrontendRichText(blank=True, default='', verbose_name='contexte'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='course',
            field=open_democracy_back.models.utils.FrontendRichText(blank=True, default='', verbose_name='déroulé'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='demometre_suggestions',
            field=open_democracy_back.models.utils.FrontendRichText(blank=True, default='', verbose_name='suggestions démomètre'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='improvement_observations',
            field=open_democracy_back.models.utils.FrontendRichText(blank=True, default='', verbose_name="remarques sur les mesures d'amélioration"),
        ),
        migrations.AddField(
            model_name='workshop',
            name='objectives',
            field=open_democracy_back.models.utils.FrontendRichText(blank=True, default='', verbose_name='objectifs'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='place',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='platform_suggestions',
            field=open_democracy_back.models.utils.FrontendRichText(blank=True, default='', verbose_name='suggestions sur la plateforme'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='result_observations',
            field=open_democracy_back.models.utils.FrontendRichText(blank=True, default='', verbose_name='remarques sur les résultats'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='type',
            field=models.CharField(choices=[('assessment', 'évaluation'), ('results', 'résultats')], default='assessment', max_length=10),
        ),
        migrations.AlterField(
            model_name='assessmentpayment',
            name='amount',
            field=models.FloatField(verbose_name='montant'),
        ),
    ]
