# Generated by Django 3.2.11 on 2022-06-16 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0045_auto_20220615_1358'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClosedWithRankingResponse',
        ),
    ]
