# Generated by Django 3.2.13 on 2022-06-14 08:32

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0046_auto_20220613_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referentialpage',
            name='criteria_block_title',
            field=models.CharField(blank=True, help_text="si ce champs est vide l'explication des critères d'évaluation ne s'affichera pas", max_length=68, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='referentialpage',
            name='marker_block_content',
            field=wagtail.core.fields.RichTextField(default='', help_text="s'il n'y a pas de contenu l'explication des marqueurs ne s'affichera pas", verbose_name='Contenu'),
        ),
        migrations.AlterField(
            model_name='referentialpage',
            name='marker_block_title',
            field=models.CharField(blank=True, help_text="si ce champs est vide l'explication des marqueurs ne s'affichera pas", max_length=68, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='referentialpage',
            name='pillar_block_content',
            field=wagtail.core.fields.RichTextField(default='', help_text="s'il n'y a pas de contenu l'explication des piliers ne s'affichera pas", verbose_name='Contenu'),
        ),
        migrations.AlterField(
            model_name='referentialpage',
            name='pillar_block_title',
            field=models.CharField(blank=True, help_text="si ce champs est vide l'explication des piliers ne s'affichera pas", max_length=68, verbose_name='Titre'),
        ),
    ]
