# Generated by Django 3.2.13 on 2022-06-16 15:40

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0046_auto_20220616_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='referentialpage',
            name='description',
            field=wagtail.core.fields.RichTextField(default='', verbose_name='Description'),
        ),
    ]
