# Generated by Django 3.2.11 on 2022-06-17 09:45

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtailsvg.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0046_projectpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpage',
            name='how_block_data',
            field=wagtail.core.fields.StreamField([('title', wagtail.core.blocks.CharBlock(label='Titre')), ('paragraph', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'ol', 'ul'], label='Paragraphe')), ('cards', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('svg', wagtailsvg.blocks.SvgChooserBlock()), ('title', wagtail.core.blocks.CharBlock(label='Titre')), ('details', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'ol', 'ul'], label='Descriptif')), ('link', wagtail.core.blocks.CharBlock(label='Lien en savoir plus'))]), label='Carte', label_format='Carte : {title}'))], blank=True, verbose_name='Les impacts'),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='objective_block_data',
            field=wagtail.core.fields.StreamField([('objective', wagtail.core.blocks.StructBlock([('svg', wagtailsvg.blocks.SvgChooserBlock()), ('title', wagtail.core.blocks.CharBlock(label='Titre'))], label='Objectif', label_format='Objectif : {title}'))], blank=True, verbose_name='Les objectifs'),
        ),
    ]
