# Generated by Django 3.2.19 on 2023-09-15 14:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0012_uploadeddocument'),
        ('open_democracy_back', '0046_auto_20230911_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='usagepage',
            name='training_block_intro',
            field=wagtail.fields.RichTextField(blank=True, default='Démocratie Ouverte vous propose des formations pour accompagner des évaluations DémoMètre et/ou animer des ateliers d’évaluations.', verbose_name='Intro de la section formation'),
        ),
        migrations.AddField(
            model_name='usagepage',
            name='training_block_title',
            field=models.CharField(blank=True, default='Formations certifiantes', max_length=100, verbose_name='Titre de la section formation'),
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=100, verbose_name='nom')),
                ('audience', models.CharField(max_length=200, verbose_name='public ciblé pour la formation')),
                ('description', models.CharField(max_length=300, verbose_name='description courte')),
                ('duration', models.CharField(help_text='ex une journée, une heure...', max_length=50, verbose_name='durée de la formation')),
                ('is_available_soon', models.BooleanField(default=False, help_text="si cette case est cochée, la formation ne sera pas accessible, mais l'utilisateur sera informé de sa publication prochaine", verbose_name='bientôt disponible')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Lien externe')),
                ('file', models.ForeignKey(blank=True, help_text='Ce document est ignoré si le lien externe est défini', null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtaildocs.document', verbose_name='Document lié')),
            ],
            options={
                'verbose_name': 'Formation',
            },
        ),
    ]
