# Generated by Django 3.2.19 on 2023-09-22 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0047_auto_20230915_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='royalty_payed',
        ),
    ]
