# Generated by Django 3.2.11 on 2022-06-16 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("open_democracy_back", "0047_auto_20220620_0719"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ClosedWithRankingResponse",
        ),
    ]
