# Generated by Django 3.2.13 on 2022-06-14 08:40

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0048_auto_20220614_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referentialpage',
            name='criteria_block_content',
            field=wagtail.core.fields.RichTextField(default='', verbose_name='Contenu'),
        ),
    ]
