# Generated by Django 3.2.23 on 2024-01-16 15:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import wagtail.fields


def add_default_survey(apps, _):
    Survey = apps.get_model('open_democracy_back', 'Survey')
    survey = Survey.objects.create(name='Questionnaire DémoMètre', description='Questionnaire historique du DémoMètre', is_active=True)
    survey.save()

    Pillar = apps.get_model('open_democracy_back', 'Pillar')
    Pillar.objects.all().update(survey=survey)

class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0048_remove_assessment_royalty_payed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nom')),
                ('description', wagtail.fields.RichTextField(blank=True, default='', help_text='Description du questionnaire', max_length=1024, verbose_name='Description')),
                ('is_active', models.BooleanField(default=False, verbose_name='Actif')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='thematictag',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='pillar',
            name='survey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pillars', to='open_democracy_back.survey'),
        ),
        migrations.RunPython(add_default_survey, migrations.RunPython.noop),
    ]
