# Generated by Django 3.2.11 on 2022-06-21 13:24

from django.db import migrations, models
import open_democracy_back.models.contents_models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0049_projectpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpage',
            name='who_partner_sub_block_data',
            field=wagtail.core.fields.StreamField([('group_partners', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(label='Titre')), ('description', wagtail.core.blocks.CharBlock(label='Description')), ('partners', wagtail.core.blocks.ListBlock(wagtail.snippets.blocks.SnippetChooserBlock(open_democracy_back.models.contents_models.Partner)))], label='Type de partenaires', label_format='{title}'))], blank=True, verbose_name='Partenaires - contenu'),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='who_partner_sub_block_title',
            field=models.CharField(blank=True, help_text="Si ce champ est vide le bloc ne s'affichera pas", max_length=68, verbose_name='Partenaires - titre'),
        ),
    ]
