# Generated by Django 3.2.19 on 2024-03-27 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0012_uploadeddocument'),
        ('open_democracy_back', '0049_auto_20240119_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='code',
            field=models.CharField(default='', help_text="Nom court du questionnaire pour les menus de l'interface admin", max_length=10, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='concatenated_code',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='marker',
            name='code',
            field=models.CharField(help_text='Correspond au numéro (ou lettre) de ce marqueur dans son pilier', max_length=3, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='concatenated_code',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='pillar',
            name='code',
            field=models.CharField(help_text='Correspond au numéro (ou lettre) de ce pilier', max_length=10, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='rgpdsettings',
            name='terms_of_sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='Conditions générales de vente'),
        ),
        migrations.AlterField(
            model_name='rgpdsettings',
            name='terms_of_use',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name="Conditions générales d'utilisation"),
        ),
        migrations.AlterField(
            model_name='thematictag',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='slug'),
        ),
    ]
