# Generated by Django 3.2.11 on 2022-06-17 15:21

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0049_alter_projectpage_how_block_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectpage',
            name='why_block_text',
        ),
        migrations.AddField(
            model_name='projectpage',
            name='why_block_data',
            field=wagtail.core.fields.StreamField([('paragraph', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'ol', 'ul'], label='Paragraphe')), ('image', wagtail.images.blocks.ImageChooserBlock(label='Image'))], blank=True, verbose_name='Texte'),
        ),
    ]
