# Generated by Django 3.2.11 on 2022-06-22 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0050_auto_20220621_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='closedwithscalecategoryresponse',
            name='response',
        ),
        migrations.AddField(
            model_name='closedwithscalecategoryresponse',
            name='assessment_response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='closed_with_scale_response_categories', to='open_democracy_back.assessmentresponse'),
        ),
        migrations.AddField(
            model_name='closedwithscalecategoryresponse',
            name='participation_response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='closed_with_scale_response_categories', to='open_democracy_back.participationresponse'),
        ),
        migrations.AlterField(
            model_name='closedwithscalecategoryresponse',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='closed_with_scale_category_responses', to='open_democracy_back.category'),
        ),
    ]
