# Generated by Django 3.2.11 on 2022-06-17 16:03

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks
import wagtailsvg.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0050_auto_20220617_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpage',
            name='how_block_data',
            field=wagtail.core.fields.StreamField([('title', wagtail.core.blocks.CharBlock(label='Titre')), ('richtext', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'ol', 'ul'], label='Paragraphe')), ('cards', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('svg', wagtailsvg.blocks.SvgChooserBlock(label='Icon au format svg')), ('title', wagtail.core.blocks.CharBlock(label='Titre')), ('richtext', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'ol', 'ul'], label='Descriptif')), ('link', wagtail.core.blocks.CharBlock(label='Lien en savoir plus', required=False))]), label='Cartes', label_format='Carte : {title}'))], blank=True, verbose_name='Les impacts'),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='why_block_data',
            field=wagtail.core.fields.StreamField([('richtext', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'ol', 'ul'], label='Paragraphe')), ('image', wagtail.images.blocks.ImageChooserBlock(label='Image'))], blank=True, verbose_name='Texte'),
        ),
    ]
