# Generated by Django 3.2.19 on 2024-03-28 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0050_auto_20240327_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='survey_type',
            field=models.CharField(choices=[('city', 'Commune/EPCI'), ('region', 'Région')], default='city', max_length=32, verbose_name='Type de questionnaire'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='locality_type',
            field=models.CharField(choices=[('municipality', 'Commune'), ('intercommunality', 'Intercommunalité'), ('department', 'Département'), ('region', 'Région')], default='municipality', max_length=32, verbose_name='Type de localité'),
        ),
        migrations.AlterField(
            model_name='department',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='open_democracy_back.region', verbose_name='Région'),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='municipalities', to='open_democracy_back.department', verbose_name='Département'),
        ),
    ]
