# Generated by Django 3.2.19 on 2024-04-09 08:35

from django.db import migrations, models
import django.db.migrations.operations.special
import django.db.models.deletion

def set_survey_on_assements(apps, schema_editor):
    Assessment = apps.get_model('open_democracy_back', 'Assessment')
    Survey = apps.get_model('open_democracy_back', 'Survey')
    survey = Survey.objects.first()
    for assessment in Assessment.objects.all():
        assessment.survey = survey
        assessment.save()

class Migration(migrations.Migration):

    replaces = [('open_democracy_back', '0051_auto_20240328_1417'), ('open_democracy_back', '0052_auto_20240328_1430'), ('open_democracy_back', '0053_assessment_survey'), ('open_democracy_back', '0054_auto_20240403_0933'), ('open_democracy_back', '0055_auto_20240403_1101')]

    dependencies = [
        ('open_democracy_back', '0050_auto_20240327_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='locality_type',
            field=models.CharField(choices=[('municipality', 'Commune'), ('intercommunality', 'Intercommunalité'), ('department', 'Département'), ('region', 'Région')], default='municipality', max_length=32, verbose_name='Type de localité'),
        ),
        migrations.AlterField(
            model_name='department',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='open_democracy_back.region', verbose_name='Région'),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='municipalities', to='open_democracy_back.department', verbose_name='Département'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='open_democracy_back.region', verbose_name='Région'),
        ),
        migrations.AddField(
            model_name='survey',
            name='survey_type',
            field=models.CharField(choices=[('city', 'Commune/EPCI'), ('region', 'Région')], default='city', max_length=32, verbose_name='Type de questionnaire'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='survey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='open_democracy_back.survey', verbose_name='Questionnaire'),
        ),
        migrations.RunPython(
            code=set_survey_on_assements,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AddField(
            model_name='assessment',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='open_democracy_back.department', verbose_name='Département'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='marker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='criterias', to='open_democracy_back.marker'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='pillar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='markers', to='open_democracy_back.pillar'),
        ),
        migrations.AlterField(
            model_name='question',
            name='criteria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='open_democracy_back.criteria'),
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='survey_type',
            new_name='survey_locality',
        ),
        migrations.AlterField(
            model_name='survey',
            name='survey_locality',
            field=models.CharField(choices=[('city', 'Commune/EPCI'), ('department', 'Département'), ('region', 'Région')], default='city', max_length=32, verbose_name='Type de questionnaire'),
        ),
        migrations.AddField(
            model_name='representativitycriteria',
            name='survey_locality',
            field=models.CharField(choices=[('city', 'Commune/EPCI'), ('department', 'Département'), ('region', 'Région')], default='city', max_length=32, verbose_name='Échelon questionnaire'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='survey_locality',
            field=models.CharField(choices=[('city', 'Commune/EPCI'), ('department', 'Département'), ('region', 'Région')], default='city', max_length=32, verbose_name='Échelon du questionnaire'),
        ),
    ]
