# Generated by Django 3.2.12 on 2022-06-23 13:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0051_auto_20220622_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='false_associated_score',
        ),
        migrations.RemoveField(
            model_name='question',
            name='true_associated_score',
        ),
        migrations.AddField(
            model_name='percentagerange',
            name='linearized_score',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Score associé linéarisé'),
        ),
        migrations.AddField(
            model_name='responsechoice',
            name='linearized_score',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Score associé linéarisé'),
        ),
        migrations.AlterField(
            model_name='percentagerange',
            name='associated_score',
            field=models.IntegerField(blank=True, help_text='Si pertinant', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='Score associé'),
        ),
        migrations.AlterField(
            model_name='responsechoice',
            name='associated_score',
            field=models.IntegerField(blank=True, help_text='Si pertinant', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='Score associé'),
        ),
    ]
