# Generated by Django 3.2.19 on 2024-03-28 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0051_auto_20240328_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='open_democracy_back.region', verbose_name='Région'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='survey_type',
            field=models.CharField(choices=[('city', 'Commune/EPCI'), ('region', 'Région')], default='city', max_length=32, unique=True, verbose_name='Type de questionnaire'),
        ),
    ]
