# Generated by Django 3.2.19 on 2024-04-09 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0051_auto_20240328_1417_squashed_0055_auto_20240403_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='survey_locality',
            field=models.CharField(choices=[('city', 'Commune/EPCI'), ('department', 'Département'), ('region', 'Région')], default='city', max_length=32, unique=True, verbose_name='Échelon du questionnaire'),
        ),
    ]
