# Generated by Django 3.2.13 on 2022-06-24 13:27

import django.core.validators
from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtailsvg.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0052_auto_20220623_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='height',
            field=models.IntegerField(default=60, help_text='Choisir la hauteur du logo (min 40px / max 120px)', validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(120)], verbose_name='Hauteur du logo'),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='how_block_data',
            field=wagtail.core.fields.StreamField([('title', wagtail.core.blocks.CharBlock(label='Titre')), ('richtext', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'ol', 'ul'], label='Paragraphe')), ('step', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('svg', wagtailsvg.blocks.SvgChooserBlock(help_text="Pour ajouter un SVG d'abord l'ajouter dans le menu SVG", label='Icon au format svg')), ('title', wagtail.core.blocks.CharBlock(label='Titre')), ('richtext', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'ol', 'ul'], label='Descriptif')), ('link', wagtail.core.blocks.CharBlock(label='Lien en savoir plus', required=False))]), label='Etapes', label_format='Carte : {title}'))], blank=True, verbose_name='Contenu'),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='objective_block_data',
            field=wagtail.core.fields.StreamField([('objective', wagtail.core.blocks.StructBlock([('svg', wagtailsvg.blocks.SvgChooserBlock(help_text="Pour ajouter un SVG d'abord l'ajouter dans le menu SVG", label='Icon au format svg')), ('title', wagtail.core.blocks.CharBlock(label='Titre'))], label='Objectif', label_format='Objectif : {title}'))], blank=True, verbose_name='Les objectifs'),
        ),
    ]
