# Generated by Django 3.2.23 on 2024-04-12 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0052_alter_survey_survey_locality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='thematictag',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='slug'),
        ),
    ]
