# Generated by Django 3.2.19 on 2024-04-15 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0052_alter_survey_survey_locality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='is_active',
        ),
    ]
