# Generated by Django 3.2.19 on 2024-03-28 20:18

from django.db import migrations, models
import django.db.models.deletion


def set_survey_on_assements(apps, schema_editor):
    Assessment = apps.get_model('open_democracy_back', 'Assessment')
    Survey = apps.get_model('open_democracy_back', 'Survey')
    survey = Survey.objects.first()
    for assessment in Assessment.objects.all():
        assessment.survey = survey
        assessment.save()

class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0052_auto_20240328_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='survey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='open_democracy_back.survey', verbose_name='Questionnaire'),
        ),
        migrations.RunPython(
            code=set_survey_on_assements,
            reverse_code=lambda apps, schema_editor: None
        )
    ]
