# Generated by Django 3.2.19 on 2024-04-19 08:58

from django.db import migrations, models


def fill_profiling_questions_surveys(apps, schema):
    Question = apps.get_model('open_democracy_back', 'Question')
    Survey = apps.get_model('open_democracy_back', 'Survey')
    surveys = Survey.objects.all()
    for question in Question.objects.filter(profiling_question=True):
        for survey in surveys:
            question.surveys.add(survey)


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0053_auto_20240412_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='surveys',
            field=models.ManyToManyField(blank=True, related_name='profiling_questions', to='open_democracy_back.Survey', verbose_name='Questionnaires concernés'),
        ),
        migrations.AlterField(
            model_name='thematictag',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='slug'),
        ),
        migrations.RunPython(
            fill_profiling_questions_surveys,
            migrations.RunPython.noop,
        )
    ]
