# Generated by Django 3.2.19 on 2024-04-03 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0053_assessment_survey'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='open_democracy_back.department', verbose_name='Département'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='marker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='criterias', to='open_democracy_back.marker'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='pillar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='markers', to='open_democracy_back.pillar'),
        ),
        migrations.AlterField(
            model_name='question',
            name='criteria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='open_democracy_back.criteria'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='survey_type',
            field=models.CharField(choices=[('city', 'Commune/EPCI'), ('department', 'Département'), ('region', 'Région')], default='city', max_length=32, unique=True, verbose_name='Type de questionnaire'),
        ),
    ]
