# Generated by Django 3.2.13 on 2022-06-24 13:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('open_democracy_back', '0053_auto_20220624_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='height',
            field=models.IntegerField(default=60, help_text='Choisir la hauteur du logo (min 40px / max 120px)', validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(120)], verbose_name='Hauteur'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='logo_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image', verbose_name='Logo'),
        ),
    ]
