# Generated by Django 3.2.11 on 2022-06-24 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0053_auto_20220624_1709'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['sort_order'], 'verbose_name': 'Catégorie'},
        ),
        migrations.AlterModelOptions(
            name='percentagerange',
            options={'ordering': ['sort_order'], 'verbose_name': 'Score pour une fourcette donnée', 'verbose_name_plural': 'Scores pour les différentes fourchettes'},
        ),
        migrations.AlterModelOptions(
            name='responsechoice',
            options={'ordering': ['sort_order'], 'verbose_name': 'Choix de réponse', 'verbose_name_plural': 'Choix de réponse'},
        ),
        migrations.AddField(
            model_name='partner',
            name='show_in_home_page',
            field=models.BooleanField(default=True, verbose_name="Afficher dans la page d'accueil"),
        ),
    ]
