# Generated by Django 3.2.19 on 2024-04-03 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0054_auto_20240403_0933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='survey_type',
            new_name='survey_locality',
        ),
        migrations.AddField(
            model_name='representativitycriteria',
            name='survey_locality',
            field=models.CharField(choices=[('city', 'Commune/EPCI'), ('department', 'Département'), ('region', 'Région')], default='city', max_length=32, verbose_name='Échelon du questionnaire'),
        ),
        migrations.AlterField(
            model_name='representativitycriteria',
            name='survey_locality',
            field=models.CharField(
                choices=[('city', 'Commune/EPCI'), ('department', 'Département'),
                         ('region', 'Région')], default='city', max_length=32,
                verbose_name='Échelon questionnaire'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='survey_locality',
            field=models.CharField(
                choices=[('city', 'Commune/EPCI'), ('department', 'Département'),
                         ('region', 'Région')], default='city', max_length=32,
                unique=True, verbose_name='Échelon du questionnaire'),
        ),
    ]
