# Generated by Django 3.2.13 on 2022-06-27 12:46

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0054_auto_20220624_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='criteria',
            name='explanatory',
            field=wagtail.core.fields.StreamField([('category', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(label='Titre')), ('description', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'ol', 'ul'], label='Description'))], label='Catégorie', label_format='Catégorie : {title}'))], blank=True, verbose_name='Explicatif du critère'),
        ),
    ]
