# Generated by Django 3.2.23 on 2024-04-25 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0054_auto_20240419_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thematictag',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='slug'),
        ),
    ]
