# Generated by Django 5.0.6 on 2024-06-25 10:35

import wagtail.fields
from django.db import migrations


def fill_survey_description_fr(apps, schema_editor):
    Survey = apps.get_model("open_democracy_back", "Survey")
    for survey in Survey.objects.all():
        survey.description_fr = survey.description
        survey.save()


class Migration(migrations.Migration):
    dependencies = [
        (
            "open_democracy_back",
            "0055_alter_assessmentresponse_multiple_choice_response_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="survey",
            options={
                "verbose_name": "Questionnaire",
                "verbose_name_plural": "Questionnaires",
            },
        ),
        migrations.AddField(
            model_name="survey",
            name="description_fr",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Description du questionnaire",
                max_length=1024,
                null=True,
                verbose_name="Description (fr)",
            ),
        ),
        migrations.RunPython(fill_survey_description_fr, migrations.RunPython.noop),
    ]
