# Generated by Django 3.2.25 on 2024-05-30 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0055_alter_thematictag_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('unique_choice', 'Choix unique'), ('multiple_choice', 'Choix multiple'), ('closed_with_scale', 'Fermée à échelle'), ('boolean', 'Binaire oui / non'), ('percentage', 'Pourcentage'), ('number', 'Nombre')], default='boolean', help_text='Choisir le type de question', max_length=32),
        ),
    ]
