# Generated by Django 3.2.13 on 2022-06-29 13:51

from django.db import migrations
import json

def pass_explanation_criteria_to_stremfield(apps, _):
    Criteria = apps.get_model("open_democracy_back", "Criteria")
    for criteria in Criteria.objects.all():
        raw_json = []
        if criteria.legal_frame:
            raw_json.append(
                {
                    "type": "category",
                    "value": {"title": "Cadre légal", "description": criteria.legal_frame}, 
                }
            )
        if criteria.use_case:
            raw_json.append(
                {
                    "type": "category",
                    "value": {"title": "Exemples inspirants", "description": criteria.use_case}, 
                }
            )
        if criteria.sources:
            raw_json.append(
                {
                    "type": "category",
                    "value": {"title": "Sources", "description": criteria.sources}, 
                }
            )
        if criteria.to_go_further:
            raw_json.append(
                {
                    "type": "category",
                    "value": {"title": "Pour aller plus loin", "description": criteria.to_go_further}, 
                } 
            )
        
        criteria.explanatory = json.dumps(raw_json)
        criteria.save()



class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0055_criteria_explanatory'),
    ]

    operations = [
        migrations.RunPython(pass_explanation_criteria_to_stremfield),
    ]
