# Generated by Django 5.0.6 on 2024-06-25 10:35

import wagtail.fields
from django.db import migrations
from django.db import models


fr_fields = {
    "Survey": ["description"],
    "Marker": ["description", "score_1", "score_2", "score_3", "score_4", "name"],
    "Pillar": ["description"],
    "Criteria": ["description", "name"],
    "Question": ["comments", "description", "name", "question_statement"],
    "ResponseChoice": ["description", "response_choice"],
}


def fill_models_fr_fields(apps, schema_editor):
    for model_name, fields in fr_fields.items():
        Model = apps.get_model("open_democracy_back", model_name)
        for field in fields:
            field_fr = f"{field}_fr"
            for instance in Model.objects.all():
                setattr(instance, field_fr, getattr(instance, field))
                instance.save()


class Migration(migrations.Migration):
    dependencies = [
        (
            "open_democracy_back",
            "0055_alter_assessmentresponse_multiple_choice_response_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="survey",
            options={
                "verbose_name": "Questionnaire",
                "verbose_name_plural": "Questionnaires",
            },
        ),
        migrations.AddField(
            model_name="survey",
            name="description_fr",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Description du questionnaire",
                max_length=1024,
                null=True,
                verbose_name="Description (fr)",
            ),
        ),
        migrations.AddField(
            model_name="marker",
            name="description_fr",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Description pour le référentiel",
                null=True,
                verbose_name="Description (fr)",
            ),
        ),
        migrations.AddField(
            model_name="marker",
            name="score_1_fr",
            field=models.TextField(
                blank=True,
                help_text="Signification du résultat 1, affiché dans le DémoMètre",
                null=True,
                verbose_name="Score = 1 (Signification) (fr)",
            ),
        ),
        migrations.AddField(
            model_name="marker",
            name="score_2_fr",
            field=models.TextField(
                blank=True,
                help_text="Signification du résultat 2, affiché dans le DémoMètre",
                null=True,
                verbose_name="Score = 2 (Signification) (fr)",
            ),
        ),
        migrations.AddField(
            model_name="marker",
            name="score_3_fr",
            field=models.TextField(
                blank=True,
                help_text="Signification du résultat 3, affiché dans le DémoMètre",
                null=True,
                verbose_name="Score = 3 (Signification) (fr)",
            ),
        ),
        migrations.AddField(
            model_name="marker",
            name="score_4_fr",
            field=models.TextField(
                blank=True,
                help_text="Signification du résultat 4, affiché dans le DémoMètre",
                null=True,
                verbose_name="Score = 4 (Signification) (fr)",
            ),
        ),
        migrations.AddField(
            model_name="pillar",
            name="description_fr",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Description pour le référentiel",
                null=True,
                verbose_name="Description (fr)",
            ),
        ),
        migrations.AddField(
            model_name="marker",
            name="description_en",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Description pour le référentiel",
                null=True,
                verbose_name="Description (en)",
            ),
        ),
        migrations.AddField(
            model_name="marker",
            name="score_1_en",
            field=models.TextField(
                blank=True,
                help_text="Signification du résultat 1, affiché dans le DémoMètre",
                null=True,
                verbose_name="Score = 1 (Signification) (en)",
            ),
        ),
        migrations.AddField(
            model_name="marker",
            name="score_2_en",
            field=models.TextField(
                blank=True,
                help_text="Signification du résultat 2, affiché dans le DémoMètre",
                null=True,
                verbose_name="Score = 2 (Signification) (en)",
            ),
        ),
        migrations.AddField(
            model_name="marker",
            name="score_3_en",
            field=models.TextField(
                blank=True,
                help_text="Signification du résultat 3, affiché dans le DémoMètre",
                null=True,
                verbose_name="Score = 3 (Signification) (en)",
            ),
        ),
        migrations.AddField(
            model_name="marker",
            name="score_4_en",
            field=models.TextField(
                blank=True,
                help_text="Signification du résultat 4, affiché dans le DémoMètre",
                null=True,
                verbose_name="Score = 4 (Signification) (en)",
            ),
        ),
        migrations.AddField(
            model_name="pillar",
            name="description_en",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Description pour le référentiel",
                null=True,
                verbose_name="Description (en)",
            ),
        ),
        migrations.AddField(
            model_name="survey",
            name="description_en",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Description du questionnaire",
                max_length=1024,
                null=True,
                verbose_name="Description (en)",
            ),
        ),
        migrations.AddField(
            model_name="criteria",
            name="description_en",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Description pour le référentiel",
                null=True,
                verbose_name="Description (en)",
            ),
        ),
        migrations.AddField(
            model_name="criteria",
            name="description_fr",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Description pour le référentiel",
                null=True,
                verbose_name="Description (fr)",
            ),
        ),
        migrations.AddField(
            model_name="criteria",
            name="name_en",
            field=models.CharField(
                blank=True, max_length=125, null=True, verbose_name="Nom (en)"
            ),
        ),
        migrations.AddField(
            model_name="criteria",
            name="name_fr",
            field=models.CharField(
                blank=True, max_length=125, null=True, verbose_name="Nom (fr)"
            ),
        ),
        migrations.AddField(
            model_name="marker",
            name="name_en",
            field=models.CharField(
                blank=True, max_length=125, null=True, verbose_name="Nom (en)"
            ),
        ),
        migrations.AddField(
            model_name="marker",
            name="name_fr",
            field=models.CharField(
                blank=True, max_length=125, null=True, verbose_name="Nom (fr)"
            ),
        ),
        # 60
        migrations.AddField(
            model_name="question",
            name="comments_en",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Indication affichée uniquement pour les administrateurs.",
                null=True,
                verbose_name="Commentaires (pour l'interne) (en)",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="comments_fr",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Indication affichée uniquement pour les administrateurs.",
                null=True,
                verbose_name="Commentaires (pour l'interne) (fr)",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="description_en",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Texte précisant la question et pourquoi elle est posée.",
                null=True,
                verbose_name="Description (en)",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="description_fr",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Texte précisant la question et pourquoi elle est posée.",
                null=True,
                verbose_name="Description (fr)",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="name_en",
            field=models.CharField(
                blank=True, max_length=125, null=True, verbose_name="Nom (en)"
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="name_fr",
            field=models.CharField(
                blank=True, max_length=125, null=True, verbose_name="Nom (fr)"
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="question_statement_en",
            field=models.TextField(
                blank=True, null=True, verbose_name="Enoncé de la question (en)"
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="question_statement_fr",
            field=models.TextField(
                blank=True, null=True, verbose_name="Enoncé de la question (fr)"
            ),
        ),
        migrations.AddField(
            model_name="responsechoice",
            name="description_en",
            field=models.TextField(
                blank=True,
                help_text="Texte précisant la réponse (définition, exemple, reformulation). Si la question est fermée à échelle la description ne s'affichera pas.",
                null=True,
                verbose_name="Description de la réponse (en)",
            ),
        ),
        migrations.AddField(
            model_name="responsechoice",
            name="description_fr",
            field=models.TextField(
                blank=True,
                help_text="Texte précisant la réponse (définition, exemple, reformulation). Si la question est fermée à échelle la description ne s'affichera pas.",
                null=True,
                verbose_name="Description de la réponse (fr)",
            ),
        ),
        migrations.AddField(
            model_name="responsechoice",
            name="response_choice_en",
            field=models.CharField(
                blank=True,
                max_length=510,
                null=True,
                verbose_name="Réponse possible (en)",
            ),
        ),
        migrations.AddField(
            model_name="responsechoice",
            name="response_choice_fr",
            field=models.CharField(
                blank=True,
                max_length=510,
                null=True,
                verbose_name="Réponse possible (fr)",
            ),
        ),
        migrations.RunPython(fill_models_fr_fields, migrations.RunPython.noop),
    ]
