# Generated by Django 5.0.6 on 2024-06-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("open_democracy_back", "0056_alter_survey_options_survey_description_fr"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="type",
            field=models.CharField(
                choices=[
                    ("unique_choice", "Choix unique"),
                    ("multiple_choice", "Choix multiple"),
                    ("closed_with_scale", "Fermée à échelle"),
                    ("boolean", "Binaire oui / non"),
                    ("percentage", "Pourcentage"),
                    ("number", "Nombre"),
                ],
                default="boolean",
                help_text="Choisir le type de question",
                max_length=32,
            ),
        ),
    ]
