# Generated by Django 5.0.6 on 2024-06-25 10:42

import wagtail.fields
from django.db import migrations, models


def fill_marker_and_pillar_description_fr(apps, schema_editor):
    Marker = apps.get_model("open_democracy_back", "Marker")
    for marker in Marker.objects.all():
        marker.description_fr = marker.description
        marker.score_1_fr = marker.score_1
        marker.score_2_fr = marker.score_2
        marker.score_3_fr = marker.score_3
        marker.score_4_fr = marker.score_4
        marker.save()

    Pillar = apps.get_model("open_democracy_back", "Pillar")
    for pillar in Pillar.objects.all():
        pillar.description_fr = pillar.description
        pillar.save()


class Migration(migrations.Migration):
    dependencies = [
        ("open_democracy_back", "0056_alter_survey_options_survey_description_fr"),
    ]

    operations = [
        migrations.AddField(
            model_name="marker",
            name="description_fr",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Description pour le référentiel",
                null=True,
                verbose_name="Description (fr)",
            ),
        ),
        migrations.AddField(
            model_name="marker",
            name="score_1_fr",
            field=models.TextField(
                blank=True,
                help_text="Signification du résultat 1, affiché dans le DémoMètre",
                null=True,
                verbose_name="Score = 1 (Signification) (fr)",
            ),
        ),
        migrations.AddField(
            model_name="marker",
            name="score_2_fr",
            field=models.TextField(
                blank=True,
                help_text="Signification du résultat 2, affiché dans le DémoMètre",
                null=True,
                verbose_name="Score = 2 (Signification) (fr)",
            ),
        ),
        migrations.AddField(
            model_name="marker",
            name="score_3_fr",
            field=models.TextField(
                blank=True,
                help_text="Signification du résultat 3, affiché dans le DémoMètre",
                null=True,
                verbose_name="Score = 3 (Signification) (fr)",
            ),
        ),
        migrations.AddField(
            model_name="marker",
            name="score_4_fr",
            field=models.TextField(
                blank=True,
                help_text="Signification du résultat 4, affiché dans le DémoMètre",
                null=True,
                verbose_name="Score = 4 (Signification) (fr)",
            ),
        ),
        migrations.AddField(
            model_name="pillar",
            name="description_fr",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Description pour le référentiel",
                null=True,
                verbose_name="Description (fr)",
            ),
        ),
        migrations.RunPython(fill_marker_and_pillar_description_fr, migrations.RunPython.noop),
    ]
