# Generated by Django 3.2.13 on 2022-06-29 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0056_auto_20220629_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criteria',
            name='legal_frame',
        ),
        migrations.RemoveField(
            model_name='criteria',
            name='sources',
        ),
        migrations.RemoveField(
            model_name='criteria',
            name='to_go_further',
        ),
        migrations.RemoveField(
            model_name='criteria',
            name='use_case',
        ),
    ]
