# Generated by Django 3.2.11 on 2022-06-27 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0056_auto_20220627_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participation',
            name='workshop',
        ),
        migrations.DeleteModel(
            name='Workshop',
        ),
    ]
