# Generated by Django 5.0.6 on 2024-06-25 10:44

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "open_democracy_back",
            "0057_marker_description_fr_marker_score_1_fr_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="marker",
            name="description_en",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Description pour le référentiel",
                null=True,
                verbose_name="Description (en)",
            ),
        ),
        migrations.AddField(
            model_name="marker",
            name="score_1_en",
            field=models.TextField(
                blank=True,
                help_text="Signification du résultat 1, affiché dans le DémoMètre",
                null=True,
                verbose_name="Score = 1 (Signification) (en)",
            ),
        ),
        migrations.AddField(
            model_name="marker",
            name="score_2_en",
            field=models.TextField(
                blank=True,
                help_text="Signification du résultat 2, affiché dans le DémoMètre",
                null=True,
                verbose_name="Score = 2 (Signification) (en)",
            ),
        ),
        migrations.AddField(
            model_name="marker",
            name="score_3_en",
            field=models.TextField(
                blank=True,
                help_text="Signification du résultat 3, affiché dans le DémoMètre",
                null=True,
                verbose_name="Score = 3 (Signification) (en)",
            ),
        ),
        migrations.AddField(
            model_name="marker",
            name="score_4_en",
            field=models.TextField(
                blank=True,
                help_text="Signification du résultat 4, affiché dans le DémoMètre",
                null=True,
                verbose_name="Score = 4 (Signification) (en)",
            ),
        ),
        migrations.AddField(
            model_name="pillar",
            name="description_en",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Description pour le référentiel",
                null=True,
                verbose_name="Description (en)",
            ),
        ),
        migrations.AddField(
            model_name="survey",
            name="description_en",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Description du questionnaire",
                max_length=1024,
                null=True,
                verbose_name="Description (en)",
            ),
        ),
    ]
