# Generated by Django 5.0.6 on 2024-07-05 08:55

import wagtail.blocks
import wagtail.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


fr_fields = {
    "Criteria": ["explanatory"],
    "ProfileType": ["name"],
    "Role": ["name", "description"],
    "Definition": ["word", "explanation"],
    "Category": ["category"],
    "Partner": ["name"],
    "Feedback": ["quote", "person_context"],
}


def fill_models_fr_fields(apps, schema_editor):
    for model_name, fields in fr_fields.items():
        Model = apps.get_model("open_democracy_back", model_name)
        for field in fields:
            field_fr = f"{field}_fr"
            for instance in Model.objects.all():
                setattr(instance, field_fr, getattr(instance, field))
                instance.save()


def re_generate_translation_key(apps, schema_editor):
    BlogPost = apps.get_model("open_democracy_back", "BlogPost")
    Resource = apps.get_model("open_democracy_back", "Resource")
    for instance in BlogPost.objects.all():
        instance.translation_key = uuid.uuid4()
        instance.save()
    for instance in Resource.objects.all():
        instance.translation_key = uuid.uuid4()
        instance.save()


class Migration(migrations.Migration):
    dependencies = [
        ("open_democracy_back", "0057_alter_question_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="criteria",
            name="explanatory_en",
            field=wagtail.fields.StreamField(
                [
                    (
                        "category",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.CharBlock(label="Titre")),
                                (
                                    "description",
                                    wagtail.blocks.RichTextBlock(
                                        features=["bold", "italic", "link", "ol", "ul"],
                                        label="Description",
                                    ),
                                ),
                            ],
                            label="Catégorie",
                            label_format="Catégorie : {title}",
                        ),
                    )
                ],
                blank=True,
                null=True,
                verbose_name="Explicatif du critère (sources, exemples, obligations légales ...) (fr)",
            ),
        ),
        migrations.AddField(
            model_name="criteria",
            name="explanatory_fr",
            field=wagtail.fields.StreamField(
                [
                    (
                        "category",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.CharBlock(label="Titre")),
                                (
                                    "description",
                                    wagtail.blocks.RichTextBlock(
                                        features=["bold", "italic", "link", "ol", "ul"],
                                        label="Description",
                                    ),
                                ),
                            ],
                            label="Catégorie",
                            label_format="Catégorie : {title}",
                        ),
                    )
                ],
                blank=True,
                null=True,
                verbose_name="Explicatif du critère (sources, exemples, obligations légales ...) (fr)",
            ),
        ),
        migrations.AddField(
            model_name="profiletype",
            name="name_en",
            field=models.CharField(
                blank=True, max_length=125, null=True, verbose_name="name (en)"
            ),
        ),
        migrations.AddField(
            model_name="profiletype",
            name="name_fr",
            field=models.CharField(
                blank=True, max_length=125, null=True, verbose_name="name (fr)"
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="description_en",
            field=models.TextField(
                blank=True,
                help_text="Texte précisant le rôle (définition, exemple, reformulation).",
                null=True,
                verbose_name="Description du rôle (en)",
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="description_fr",
            field=models.TextField(
                blank=True,
                help_text="Texte précisant le rôle (définition, exemple, reformulation).",
                null=True,
                verbose_name="Description du rôle (fr)",
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="name_en",
            field=models.CharField(
                blank=True, max_length=125, null=True, verbose_name="Nom (en)"
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="name_fr",
            field=models.CharField(
                blank=True, max_length=125, null=True, verbose_name="Nom (fr)"
            ),
        ),
        migrations.AddField(
            model_name="definition",
            name="explanation_en",
            field=wagtail.fields.RichTextField(
                blank=True, null=True, verbose_name="explication (en)"
            ),
        ),
        migrations.AddField(
            model_name="definition",
            name="explanation_fr",
            field=wagtail.fields.RichTextField(
                blank=True, null=True, verbose_name="explication (fr)"
            ),
        ),
        migrations.AddField(
            model_name="definition",
            name="word_en",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="mot (en)"
            ),
        ),
        migrations.AddField(
            model_name="definition",
            name="word_fr",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="mot (fr)"
            ),
        ),
        migrations.AlterField(
            model_name="criteria",
            name="explanatory_en",
            field=wagtail.fields.StreamField(
                [
                    (
                        "category",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.CharBlock(label="Titre")),
                                (
                                    "description",
                                    wagtail.blocks.RichTextBlock(
                                        features=["bold", "italic", "link", "ol", "ul"],
                                        label="Description",
                                    ),
                                ),
                            ],
                            label="Catégorie",
                            label_format="Catégorie : {title}",
                        ),
                    )
                ],
                blank=True,
                null=True,
                verbose_name="Explicatif du critère (sources, exemples, obligations légales ...) (en)",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="category_en",
            field=models.CharField(
                blank=True,
                help_text="Permet de répondre à la même question pour différentes catégories",
                max_length=128,
                null=True,
                verbose_name="Categorie (en)",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="category_fr",
            field=models.CharField(
                blank=True,
                help_text="Permet de répondre à la même question pour différentes catégories",
                max_length=128,
                null=True,
                verbose_name="Categorie (fr)",
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="locale",
            field=models.ForeignKey(
                default=1,
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtailcore.locale",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="blogpost",
            name="translation_key",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name="feedback",
            name="person_context_en",
            field=models.CharField(
                blank=True,
                help_text="Exemple : Elu de Strasbourg, Membre de Démocratie Ouverte, Habitant de Toulouse ... ",
                max_length=64,
                null=True,
                verbose_name="Context de la personne (en)",
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="person_context_fr",
            field=models.CharField(
                blank=True,
                help_text="Exemple : Elu de Strasbourg, Membre de Démocratie Ouverte, Habitant de Toulouse ... ",
                max_length=64,
                null=True,
                verbose_name="Context de la personne (fr)",
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="quote_en",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Citation (en)"
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="quote_fr",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Citation (fr)"
            ),
        ),
        migrations.AddField(
            model_name="partner",
            name="name_en",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="Nom (en)"
            ),
        ),
        migrations.AddField(
            model_name="partner",
            name="name_fr",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="Nom (fr)"
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="locale",
            field=models.ForeignKey(
                default=1,
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtailcore.locale",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="resource",
            name="translation_key",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.RunPython(re_generate_translation_key, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name="blogpost",
            unique_together={("translation_key", "locale")},
        ),
        migrations.AlterUniqueTogether(
            name="resource",
            unique_together={("translation_key", "locale")},
        ),
        migrations.RunPython(fill_models_fr_fields, migrations.RunPython.noop),
    ]
