# Generated by Django 3.2.11 on 2022-06-27 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0058_auto_20220627_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='name',
            field=models.CharField(default='', max_length=128, verbose_name='Nom'),
        ),
    ]
