# Generated by Django 5.0.6 on 2024-07-08 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("open_democracy_back", "0059_alter_category_options_and_more"),
        ("wagtaildocs", "0013_delete_uploadeddocument"),
    ]

    operations = [
        migrations.AddField(
            model_name="rgpdsettings",
            name="confidentiality_policy_en",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="confidentiality_policys_en",
                to="wagtaildocs.document",
                verbose_name="Politique de confidentialité (en)",
            ),
        ),
        migrations.AddField(
            model_name="rgpdsettings",
            name="confidentiality_policy_fr",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="confidentiality_policys_fr",
                to="wagtaildocs.document",
                verbose_name="Politique de confidentialité (fr)",
            ),
        ),
        migrations.AddField(
            model_name="rgpdsettings",
            name="content_license_en",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="content_licenses_en",
                to="wagtaildocs.document",
                verbose_name="Licence Contenu (en)",
            ),
        ),
        migrations.AddField(
            model_name="rgpdsettings",
            name="content_license_fr",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="content_licenses_fr",
                to="wagtaildocs.document",
                verbose_name="Licence Contenu (fr)",
            ),
        ),
        migrations.AddField(
            model_name="rgpdsettings",
            name="legal_mention_en",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="legal_mentions_en",
                to="wagtaildocs.document",
                verbose_name="Mentions légales (en)",
            ),
        ),
        migrations.AddField(
            model_name="rgpdsettings",
            name="legal_mention_fr",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="legal_mentions_fr",
                to="wagtaildocs.document",
                verbose_name="Mentions légales (fr)",
            ),
        ),
        migrations.AddField(
            model_name="rgpdsettings",
            name="terms_of_sale_en",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="terms_of_sales_en",
                to="wagtaildocs.document",
                verbose_name="Conditions générales de vente (en)",
            ),
        ),
        migrations.AddField(
            model_name="rgpdsettings",
            name="terms_of_sale_fr",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="terms_of_sales_fr",
                to="wagtaildocs.document",
                verbose_name="Conditions générales de vente (fr)",
            ),
        ),
        migrations.AddField(
            model_name="rgpdsettings",
            name="terms_of_use_en",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="terms_of_uses_en",
                to="wagtaildocs.document",
                verbose_name="Conditions générales d'utilisation (en)",
            ),
        ),
        migrations.AddField(
            model_name="rgpdsettings",
            name="terms_of_use_fr",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="terms_of_uses_fr",
                to="wagtaildocs.document",
                verbose_name="Conditions générales d'utilisation (fr)",
            ),
        ),
    ]
