# Generated by Django 5.0.8 on 2024-09-10 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("open_democracy_back", "0061_auto_20240708_1535"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profiletype",
            name="name_en",
            field=models.CharField(
                blank=True, max_length=125, null=True, verbose_name="nom (en)"
            ),
        ),
        migrations.AlterField(
            model_name="profiletype",
            name="name_fr",
            field=models.CharField(
                blank=True, max_length=125, null=True, verbose_name="nom (fr)"
            ),
        ),
    ]
