# Generated by Django 5.0.8 on 2024-10-10 16:21

from django.db import migrations, models


fr_fields = {
    "AssessmentType": [
        "for_who",
        "what",
        "for_what",
        "results",
        "price",
    ],
}


def fill_models_fr_fields(apps, schema_editor):
    for model_name, fields in fr_fields.items():
        Model = apps.get_model("open_democracy_back", model_name)
        for field in fields:
            field_fr = f"{field}_fr"
            for instance in Model.objects.all():
                setattr(instance, field_fr, getattr(instance, field))
                instance.save()


class Migration(migrations.Migration):
    dependencies = [
        (
            "open_democracy_back",
            "0062_alter_profiletype_name_en_alter_profiletype_name_fr",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="assessmenttype",
            name="for_what_en",
            field=models.CharField(
                blank=True,
                max_length=510,
                null=True,
                verbose_name="Ce que ça permet (en)",
            ),
        ),
        migrations.AddField(
            model_name="assessmenttype",
            name="for_what_fr",
            field=models.CharField(
                blank=True,
                max_length=510,
                null=True,
                verbose_name="Ce que ça permet (fr)",
            ),
        ),
        migrations.AddField(
            model_name="assessmenttype",
            name="for_who_en",
            field=models.CharField(
                blank=True,
                max_length=510,
                null=True,
                verbose_name="A qui c'est adressé (en)",
            ),
        ),
        migrations.AddField(
            model_name="assessmenttype",
            name="for_who_fr",
            field=models.CharField(
                blank=True,
                max_length=510,
                null=True,
                verbose_name="A qui c'est adressé (fr)",
            ),
        ),
        migrations.AddField(
            model_name="assessmenttype",
            name="price_en",
            field=models.CharField(
                blank=True, max_length=510, null=True, verbose_name="Le prix (en)"
            ),
        ),
        migrations.AddField(
            model_name="assessmenttype",
            name="price_fr",
            field=models.CharField(
                blank=True, max_length=510, null=True, verbose_name="Le prix (fr)"
            ),
        ),
        migrations.AddField(
            model_name="assessmenttype",
            name="results_en",
            field=models.CharField(
                blank=True, max_length=510, null=True, verbose_name="Les résultats (en)"
            ),
        ),
        migrations.AddField(
            model_name="assessmenttype",
            name="results_fr",
            field=models.CharField(
                blank=True, max_length=510, null=True, verbose_name="Les résultats (fr)"
            ),
        ),
        migrations.AddField(
            model_name="assessmenttype",
            name="what_en",
            field=models.CharField(
                blank=True,
                max_length=510,
                null=True,
                verbose_name="Ce que ça contient (en)",
            ),
        ),
        migrations.AddField(
            model_name="assessmenttype",
            name="what_fr",
            field=models.CharField(
                blank=True,
                max_length=510,
                null=True,
                verbose_name="Ce que ça contient (fr)",
            ),
        ),
        migrations.RunPython(fill_models_fr_fields, migrations.RunPython.noop),
    ]
