# Generated by Django 5.0.8 on 2024-10-14 08:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("open_democracy_back", "0063_assessmenttype_for_what_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="name_en",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Nom (en)"
            ),
        ),
        migrations.AddField(
            model_name="survey",
            name="name_fr",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Nom (fr)"
            ),
        ),
    ]
