# Generated by Django 5.0.8 on 2024-10-14 11:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("open_democracy_back", "0064_survey_name_en_survey_name_fr"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="title",
            field=models.CharField(max_length=128, verbose_name="titre"),
        ),
        migrations.AlterField(
            model_name="resource",
            name="title",
            field=models.CharField(max_length=128, verbose_name="titre"),
        ),
    ]
