# Generated by Django 5.0.9 on 2024-10-25 08:52

import wagtail.fields
from django.db import migrations, models

EN_TRANSLATIONS = {
    "CATÉGORIE PROFESSIONNELLE": "PROFESSIONAL CATEGORY",
    "TRANCHE D'ÂGE": "AGE GROUP",
    "GENRE": "GENDER",
    "LIEU DE RÉSIDENCE": "PLACE OF RESIDENCE",
    "QUARTIER DE RÉSIDENCE": "NEIGHBORHOOD OF RESIDENCE",
}


def fill_models_fr_fields(apps, _):
    for instance in apps.get_model(
        "open_democracy_back", "RepresentativityCriteria"
    ).objects.all():
        instance.name_fr = instance.name
        instance.explanation_fr = instance.explanation
        instance.name_en = EN_TRANSLATIONS.get(instance.name)
        instance.save()


class Migration(migrations.Migration):

    dependencies = [
        (
            "open_democracy_back",
            "0065_alter_blogpost_title_alter_resource_title",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="representativitycriteria",
            name="explanation_en",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="L'explication doit aider l'utilisateur à savoir quel pourcentage indiquer et expliciter le pourcentage renseigné par défault",
                null=True,
                verbose_name="Explication (en)",
            ),
        ),
        migrations.AddField(
            model_name="representativitycriteria",
            name="explanation_fr",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="L'explication doit aider l'utilisateur à savoir quel pourcentage indiquer et expliciter le pourcentage renseigné par défault",
                null=True,
                verbose_name="Explication (fr)",
            ),
        ),
        migrations.AddField(
            model_name="representativitycriteria",
            name="name_en",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="Nom (en)"
            ),
        ),
        migrations.AddField(
            model_name="representativitycriteria",
            name="name_fr",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="Nom (fr)"
            ),
        ),
        migrations.RunPython(
            code=fill_models_fr_fields,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
