# Generated by Django 5.0.9 on 2024-10-23 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("open_democracy_back", "0065_alter_blogpost_title_alter_resource_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="representativitycriteria",
            name="survey_locality",
            field=models.CharField(
                choices=[
                    ("city", "Commune"),
                    ("epci", "EPCI"),
                    ("department", "Département"),
                    ("region", "Région"),
                ],
                default="city",
                max_length=32,
                verbose_name="Échelon questionnaire",
            ),
        ),
        migrations.AlterField(
            model_name="survey",
            name="survey_locality",
            field=models.CharField(
                choices=[
                    ("city", "Commune"),
                    ("epci", "EPCI"),
                    ("department", "Département"),
                    ("region", "Région"),
                ],
                default="city",
                max_length=32,
                unique=True,
                verbose_name="Échelon du questionnaire",
            ),
        ),
    ]
